### ISSUE TITLE
Module mallocator is in file 'std/experimental/allocator/mallocator.d' which cannot be read

### ISSUE THREAD

**Issue by aaronhyperum** [buggins/dlangui#102]
Here's the log:

Home$ dub build --force
Fetching libdparse ~master (getting selected version)...
Placing libdparse ~master to /Users/Home/.dub/packages/...
WARNING: A deprecated branch based version specification is used for the dependency libdparse. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.
WARNING: A deprecated branch based version specification is used for the dependency dlangui. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.
Building libdparse ~master configuration "library", build type debug.
Running dmd...
../../.dub/packages/libdparse-master/src/std/d/parser.d(7): Error: module mallocator is in file 'std/experimental/allocator/mallocator.d' which cannot be read
import path[0] = ../../.dub/packages/libdparse-master/src
import path[1] = /Library/D/dmd/src/phobos
import path[2] = /Library/D/dmd/src/druntime/import
FAIL ../../.dub/packages/libdparse-master/.dub/build/library-debug-posix.osx-x86_64-dmd_2068-FA5C6696890D20F798C7037C3D980FAA/ dparse staticLibrary
Error executing command build:
dmd failed with exit code 1.

On a Mac OSX running latest Yosemite.
Thanks for reading.

**Comment by BBasile** [comment]
The problem comes from a sub module (libdparse). The DUB description for this module is outdated:
I've proposed the author an update:

https://github.com/Hackerpilot/libdparse/pull/66 

wait for it to be accepted and then try again.

**Comment by buggins** [comment]
Fixed in libdparse
