### ISSUE TITLE
Look and feel

### ISSUE THREAD

**Issue by karabuta** [buggins/dlangui#104]
First of all, thanks for creating this amazing GUI library. I feel very comfortable with the API design and naming conventions at the moment. But I wanted to know if you plan on improving the UI look and feel in the near future? I am referring to the icons, background images, gradients, etc. At the moment it looks great but it can be better.

Moreover, I can help with icons if you need hands on that.

**Comment by buggins** [comment]
DlangUI supports themed look & feel
Almost everything can be changed
Check views/res directory -- look at theme_default.xml, theme_dark.xml
When application is built w/o EmbedStandardResources version definition, resources will be taken from /res folder near to application executable. It can be used to play with modified / experimental resources.
Themes are a bit similar to ones in Android.

**Comment by whitebyte** [comment]
Hi! Are there any plans for DlangUI to detect and mimic system colorscheme and widgets style? Right now this is the biggest concern that prevents from using DlangUI in production.

**Comment by buggins** [comment]
It's possible to create separate themes for Windows, OSX, Gnome, KDE and apply them based on build platform.

**Comment by buggins** [comment]
Current look & feel is mostly based on screenshots from VisualStudio under Windows.

**Comment by karabuta** [comment]
Will the current look and feel be enhanced just a little bit?

**Comment by buggins** [comment]
Could you please describe what is wrong?
Changing of theme is easy - correcting .png and .xml files

**Comment by karabuta** [comment]
Maybe towards something similar to this get us closer to VisualStudio screenshot.
![79533_990x617](https://cloud.githubusercontent.com/assets/8314648/11449257/81b2db80-9566-11e5-8437-00e6a0afcf77.jpg)

**Comment by buggins** [comment]
Changed look & feel for scrollbars.
To check, try 
     dub run dlangui:spreadsheet
