### ISSUE TITLE
Linux build: font paths are hardcoded.

### ISSUE THREAD

**Issue by buggins** [buggins/dlangui#11]
Implement fontconfig support for reading list of available fonts.

**Comment by buggins** [comment]
should work on Arch now

**Comment by MyLittleRobo** [comment]
Would not it better to use [FcConfigGetFontDirs](http://www.freedesktop.org/software/fontconfig/fontconfig-devel/fcconfiggetfontdirs.html)? I'm not sure if there's fontconfig binding for D though.

I faced the same problem in my [standardpaths library](https://github.com/MyLittleRobo/standardpaths) and even implemented some kind of [fontconfig support](https://github.com/MyLittleRobo/standardpaths/blob/master/source/standardpaths.d#L543) myself, but left it for special **version**.

**Comment by buggins** [comment]
When using FontConfig, it's better get all font properties instead of just list of directories.

**Comment by MyLittleRobo** [comment]
So what about libfontconfig binding? I could not find deimos nor derelict-like binding. If it's still not there I could make one to help the project.

**Comment by buggins** [comment]
FontConfig support is implemented. Tested on Ubuntu.

**Comment by schuetzm** [comment]
Works now on openSUSE 13.2, BUT: It seems it scans all fonts on startup :-( This is really slow, the first start took half a minute on my computer, subsequent starts still need several seconds.

**Comment by buggins** [comment]
Thanks! Going to optimize it.

**Comment by buggins** [comment]
Optimization is done.

**Comment by schuetzm** [comment]
Great! It starts up immediately now.
