### ISSUE TITLE
Textbox behaviour

### ISSUE THREAD

**Issue by default0** [buggins/dlangui#148]
When working on DlangIDE I noticed that textboxes have two differences to the way my muscle memory works for them:
If you hold shift and click on the text, the cursor just jumps to the place you clicked on, instead of creating a selection between its last position and the position you clicked at.
If you use tab to give focus to a textbox, it does not automatically select all contents of the textbox.

Should we change both of these / were they oversights or is this behaviour intended?

**Comment by buggins** [comment]
I think it has to be fixed

**Comment by default0** [comment]
#175

**Comment by buggins** [comment]
Working ok for me. Checked on dlangui examples/helloworld
Closing issue
