### ISSUE TITLE
Different font size in buttons when hovered or selected.

### ISSUE THREAD

**Issue by Lastin** [buggins/dlangui#150]
As shown below:
(https://cloud.githubusercontent.com/assets/5638394/12533372/105f1d12-c226-11e5-95ca-78fd46fb9764.png)
(https://cloud.githubusercontent.com/assets/5638394/12533375/28c61e8c-c226-11e5-85b9-b4d4ae842605.png)
Seems that text only renders within the boundaries of the default font size after hovering or deselecting.

**Comment by buggins** [comment]
How did you set font size?
Could you provide some code used to create these buttons?

**Comment by Lastin** [comment]
I've added you to collaborators, have a look:
https://github.com/Lastin/AlienCivilisations/blob/master/AlienCivilisations/src/screens/menu.d

**Comment by buggins** [comment]
Reproduced

**Comment by buggins** [comment]
Workaround is possible: define theme with modified BUTTON and BUTTON_LABEL styles

**Comment by buggins** [comment]
Fixed.
