### ISSUE TITLE
Reveal in Explorer

### ISSUE THREAD

**Issue by default0** [buggins/dlangui#151]
I think this is something that many applications will want to do.
There is a cross-plattform solution based on Qt [here](http://stackoverflow.com/questions/3490336/how-to-reveal-in-finder-or-show-in-explorer-with-qt), however I don't really understand how the Mac OS part works, nor could I test if it does since I don't have any machine running that.
That said, having this functionality available in DlangUI would be neat.
I imagine an API like this:
```d
showInFileManager(string path)
```
Where if path refers to a file on the file system and the OS supports it, the file will be automatically selected, and if path refers to a directory the directory will simply be opened.

If someone can tell me how I can test possible solutions for Mac OS I can give this a shot myself.

**Comment by buggins** [comment]
Works under windows

**Comment by buggins** [comment]
Not tested under Linux and OSX.
To test, open any File Dialog, right click on file or directory, choose Show In File Manager from context menu.
