### ISSUE TITLE
How serious is DlangUI?

### ISSUE THREAD

**Issue by dossan** [buggins/dlangui#164]
I would like to know how serious and mature is this GUI toolkit. Do you see a useful future for it? Who's supporting it apart from you?

**Comment by buggins** [comment]
It depends on what do you mean by serious.

Would not DlangUI project be abandoned in future?
Does this project have enough features?

**Comment by dossan** [comment]
By serious I mean that it supports what a commonly used GUI toolkit for a more mature language supports and if it will be still supported.

**Comment by buggins** [comment]
Most of commonly used controls are implemented in DlangUI.
At least, widget set enough to write IDE.
DlangUI is cross platform - works on Windows, Linux, OSX, and in future it's planned to support mobile platforms - Android and iOS.
Missing some features like HTML view and rich text editor.

So far, DlangUI is under active development.
If project would be abandoned by author, someone may fork it and continue development.
