### ISSUE TITLE
../../.dub/packages/dlangui-0.7.64/dlangui/src/dlangui/graphics/scene/mesh.d(73,16): Error: cannot implicitly convert expression (cast(ulong)this._vertexSize * 4LU) of type ulong to int d

### ISSUE THREAD

**Issue by ajvincent** [buggins/dlangui#170]
Found while trying to do |dub build --force| on dlangide.

[ajvincent@localhost dlangide]$ dmd --version
DMD64 D Compiler v2.070.0
Copyright (c) 1999-2015 by Digital Mars written by Walter Bright

**Comment by ajvincent** [comment]
I think this was fixed by https://github.com/buggins/dlangui/commit/60a074e66573e6c622039f9dff1c21aa74b53a92 - only it wasn't tagged for a release to dub yet.

**Comment by buggins** [comment]
Added label
