### ISSUE TITLE
It should be possible to call executeInUiThread on shared instances of Window/Widget

### ISSUE THREAD

**Issue by gizmomogwai** [buggins/dlangui#176]
As this method is allowed to be called from different threads (e.g. background thread, as stated in the documentation) this should be a shared method (otherwise the background thread has to get a shared instance of a Window or Widget and cast the shared away).

**Comment by buggins** [comment]
I'm just calling it from other thread and do not bother

**Comment by gizmomogwai** [comment]
Will close this issue, I am not familiar enough with shared. It seems, as if there is no such thing as a shared method, so the thing I suggested is not even possible. Thanks for answering.
