### ISSUE TITLE
OpenGL bindings not loading correctly on windows

### ISSUE THREAD

**Issue by Maeriden** [buggins/dlangui#180]
The hello world example program crashes with an access violation error when it tries to call glCreateShader inside GLProgram.compileShader.
I tried adding, right before the call to glCreateShader:
`
if(glCreateShader is null)
{
    throw new Exception("compileShader: glCreateShader is NULL");
}
`
in the log I get the following stack trace (line numbers may be slightly inconsistent)

UIAppMain exception: object.Exception@\dlangui-master\src\dlangui\graphics\glsupport.d(158): compileShader: glCreateShader is NULL

0x00496D00 in uint dlangui.graphics.glsupport.GLProgram.compileShader(immutable(char)[], uint) at \dlangui-master\src\dlangui\graphics\glsupport.d(161)
0x00496FB5 in bool dlangui.graphics.glsupport.GLProgram.compile() at \dlangui-master\src\dlangui\graphics\glsupport.d(212)
0x00497507 in bool dlangui.graphics.glsupport.GLSupport.initShaders() at \dlangui-master\src\dlangui\graphics\glsupport.d(610)
0x004ABA8A in bool dlangui.graphics.glsupport.initGLSupport(bool) at \dlangui-master\src\dlangui\graphics\glsupport.d(553)
0x00498F35 in bool dlangui.platforms.windows.winapp.SharedGLContext.init(void_) at \dlangui-master\src\dlangui\platforms\windows\winapp.d(179)
0x00470092 in dlangui.platforms.windows.winapp.Win32Window dlangui.platforms.windows.winapp.Win32Window.__ctor(dlangui.platforms.windows.winapp.Win32Platform, immutable(dchar)[], dlangui.platforms.common.platform.Window, uint, uint, uint) at \dlangui-master\src\dlangui\platforms\windows\winapp.d(270)
0x00431D57 in dlangui.platforms.common.platform.Window dlangui.platforms.windows.winapp.Win32Platform.createWindow(immutable(dchar)[], dlangui.platforms.common.platform.Window, uint, uint, uint) at \dlangui-master\src\dlangui\platforms\windows\winapp.d(830)
0x004030F5 in UIAppMain at \main.d(16)
0x00429023 in int dlangui.platforms.windows.winapp.myWinMain(void_, void_, char_, int) at \dlangui-master\src\dlangui\platforms\windows\winapp.d(1086)
0x0040FE24 in DLANGUIWinMain at \dlangui-master\src\dlangui\platforms\windows\winapp.d(967)
0x0040304A in WinMain at \dlangui-master\src\dlangui\platforms\common\platform.d(1422)
0x00540676 in WinMainCRTStartup
0x750A336A in BaseThreadInitThunk
0x77129882 in RtlInitializeExceptionChain
0x77129855 in RtlInitializeExceptionChain

I tried adding glCreateShader to the list of used symbols in gl3MissingSymFunc, but it seems it doesn't throw anyway. DerelictGL.reload is called successfully according to the log file.

Now, I am currently using a very old pc, with a very old video card of unknown model. I have not installed vendor drivers, but I do have opengl32.dll in my system32 folder.
I don't know this is relevant, but I thought I'd report the issue anyway so you know that there could be problems.

Windows 7 64bit, dmd 2.070.0, dlangui version dub ~master, compiled with "dub build".

**Comment by buggins** [comment]
Is this issue fixed now?

**Comment by Maeriden** [comment]
I don't have the computer anymore so I cannot test.
Nobody commented on the issue in over a year. Since it happened only on very outdated hardware I guess it's safe to close it.

**Comment by buggins** [comment]
ok.
