### ISSUE TITLE
Implement toggle switch

### ISSUE THREAD

**Issue by karabuta** [buggins/dlangui#181]
Do you plan on adding a toggle switch to the widgets. Quite a handy one for a modern UI. Just like you find in android UI or Gtk :)

**Comment by karabuta** [comment]
??

**Comment by buggins** [comment]
It can be easy done by creating new style for checkbox
Get drawables from Android, and specify them in theme
Unfortunately, I have no time to implement it right now

**Comment by karabuta** [comment]
Ok. Hoping it will added sometime in the future.

**Comment by buggins** [comment]
Implemented - SwitchWidget

**Comment by karabuta** [comment]
Great work!
