### ISSUE TITLE
Add MainMenu with DML

### ISSUE THREAD

**Issue by default0** [buggins/dlangui#182]
Currently, DML seems to disallow creation of a MainMenu. Ideally, I would like to create all parts of my UI with DML, but since I need a MainMenu, I can't do that.

**Comment by buggins** [comment]
It's easy to add creation of main menu, but requires some additional work to support adding of menu items.

**Comment by buggins** [comment]
Partially implemented: you can add `Menu {}` inside DML
But assignment of menu items is possible only manually from code using MainMenu.menuItems property:

        window.mainWidget = parseML(q{
            VerticalLayout {
                margins: 10
                MainMenu {}
                TextWidget { text: "Hello World example for DlangUI"; textColor: "red"; fontSize: 150%; fontWeight: 800; fontFace: "Arial" }
          ...

        MenuItem mainMenuItems = new MenuItem();
        MenuItem fileItem = new MenuItem(new Action(1, "MENU_FILE"));
        fileItem.add(new Action(2, "MENU_FILE_OPEN"c, "document-open", KeyCode.KEY_O, KeyFlag.Control));
        fileItem.add(new Action(3, "MENU_FILE_SAVE"c, "document-save", KeyCode.KEY_S, KeyFlag.Control));
        mainMenuItems.add(fileItem);
        window.mainWidget.childById!MainMenu("MAIN_MENU").menuItems = mainMenuItems;
