### ISSUE TITLE
Basic 3D scene drawing capabilities

### ISSUE THREAD

**Issue by buggins** [buggins/dlangui#183]
Meshes, cameras, shaders, scene.
It should be possible to draw custom 3D scenes in UI.

**Comment by karabuta** [comment]
Thats great! Does it currently support loading external modeled assets (like from blender)?

**Comment by karabuta** [comment]
Also was it designed with an inbuilt physics engine or such that one can used another physics engine.

**Comment by buggins** [comment]
No model import at the moment. But will be possible in future.
Physics - will be added if somebody would need it.

**Comment by buggins** [comment]
Using dlangui/examples/d3d as test app for Scene3d

Now trying to get shader + VBO/VAO working

**Comment by karabuta** [comment]
:+1:

**Comment by buggins** [comment]
Still cannot get my shared working.
Probably something is wrong with VAO/VBO buffer implementation.
Could someone check please?
GLVertexBuffer, Mesh, dlangui/examples/d3d

**Comment by drug007** [comment]
Why not use [gfm](https://github.com/d-gamedev-team/gfm) for example?

**Comment by buggins** [comment]
Drawing itself is working (examples/d3d)
Some issues with 3d math.

**Comment by buggins** [comment]
OBJ loading and lighting seems working

**Comment by laberba** [comment]
:+1:

**Comment by buggins** [comment]
I think this issue can be closed.
Main functionality is working.
Additional features may be added under separate issues.
