### ISSUE TITLE
dlangui:example1 crashes when clicking on File->Open menu

### ISSUE THREAD

**Issue by FreeSlave** [buggins/dlangui#188]
Having dmd 2.070.2 on Windows 8.1 x64. 
Running example1 via
```dub run --build=debug dlangui:example1```
When clicking on Open action in File menu, I get crash. Visual Studio debugger points to this code in gldrawbuf.d:

```
void drawItem(GLCacheItem item, Rect dstrc, Rect srcrc, uint color, uint options, Rect * clip, int rotationAngle) {
            if (_needUpdateTexture)
                updateTexture();
            if (_texture.ID != 0) {   //// <- this line
```

**Comment by MyLittleRobo** [comment]
Note: issue does not appear in SDL version. So it's something with winapi-based code.

**Comment by buggins** [comment]
Reproduced.
It's some issue with OpenGL contexts when there are two windows.

**Comment by buggins** [comment]
Seems fixed.
