### ISSUE TITLE
Fonts look blurred in example1

### ISSUE THREAD

**Issue by MyLittleRobo** [buggins/dlangui#190]
![example1-fonts](https://cloud.githubusercontent.com/assets/5596503/13669342/df9e53b4-e6d3-11e5-8eff-0407326607ff.png)

Fonts are weird, especially on the second line (Misc, Long list, etc.)
Running on Windows 8.1

**Comment by buggins** [comment]
Try to delete libfreetype-6.dll from directory with example1.exe - and run it again. Does it look better?

**Comment by MyLittleRobo** [comment]
![example1-fonts-no-freetype](https://cloud.githubusercontent.com/assets/5596503/13696406/352d7942-e777-11e5-9097-f9e47086c347.png)
It uses other font, but still tab names still look a bit dirty.

**Comment by buggins** [comment]
Tabs really look strange.
Will try to fix.

**Comment by buggins** [comment]
Fixed double drawing of tab header
