### ISSUE TITLE
fontFace set only sometimes works?

### ISSUE THREAD

**Issue by TheGag96** [buggins/dlangui#203]
I'm trying to set the font of a SourceEdit to "Source Code Pro" which works just fine when trying it out on the ML editor like this:

    VerticalLayout {
        EditBox  {
            fontFace: "Source Code Pro"
        }
    }

But my own program is having none of it (even when using that same example as the mainWidget). Also, other features like fontWeight appear to not do anything either. I tried even simulating the editor by having a button parse out that example after clicking it, nothing changed. Not sure what the problem is.

Windows 8.1 64-bit.

**Comment by buggins** [comment]
Probably, it's because ML editor does not use FreeType, but your program does.
FreeType support under windows adds only some limited set of fonts to available fonts list.
Once your program built, try to remove libfreetype-6.dll which is placed here by DUB
Another solution - specify configuration for dlangui which doesnt have freetype support.

**Comment by TheGag96** [comment]
Hm... Removing the .dll didn't seem to do it. How would I configure it to specifically *not* use freetype? There doesn't seem to be a DONT_USE_FREETYPE anywhere, haha.

**Comment by buggins** [comment]
You can use dlangui configuration "minimal" - but as well it turns off OpenGL support and uses software renderer. (If software rendering performance is suitable for your app, you can see benefit: less memory consumption)
Probably it makes sense to either remove freetype from default windows configuration or create new one with OpenGL but W/O freetype.

**Comment by TheGag96** [comment]
This thing is just a simple text editor with some buttons, so I suppose software rendering is okay. However, what stinks is that special characters like ← don't work in the software renderer as button text, but do with freetype. Also, for whatever reason I couldn't set the minimal flag using the SDLang version of dub configs (only a json file would do it). subConfigurations "dlangui" "minimal" would be the right syntax, yes?

**Comment by buggins** [comment]
dlangui minimal configuration uses just pure Win32 API w/o OpenGL neither FreeType
Software renderer may use wither Win32 fonts or Freetype
If some character is not visible, it's missing in font. Some improvement needed for font managers, to add missing character substitution / fallback fonts.

**Comment by buggins** [comment]
I've disabled FREETYPE in default configuration under windows.
Now all Windows fonts should be available.
Please reopen this issue if it still does not work for you.
