### ISSUE TITLE
On Win7x64 build doesn't work

### ISSUE THREAD

**Issue by XuTpuK** [buggins/dlangui#212]
I cloned repository with all deps. `dub` (which has no access to Inet) complained:
> Root package dlangui contains reference to invalid package x11 >=1.0.13 <1.1.0

Why x11 is needed in Windows - hell knows.

OK, let's build thru VS2015! Opened solution `dlangui-msvc.sln` has missing projects `dmdbug` and `dwindow-visuald`. Again bad surprise.

**Comment by buggins** [comment]
DUB requires inet access to get dependencies. There is some DUB command to specify local package location, but I never used it. I believe it could help of deps/ packages are registered in DUB.
X11 is not needed for windows, but DUB by some reason fetches all dependencies.

I've removed dmdbug and dwindow from solution. Now visuald build should work.

**Comment by MyLittleRobo** [comment]
My guess is that dub downloads dependencies for all configurations. x11 configuration is listed without platform restrictions, so it's downloaded too. Maybe specifying "platforms" property will help.
See [Configurations format](http://code.dlang.org/package-format?lang=json#configurations)

**Comment by buggins** [comment]
Does this issue still exist with latest DUB?

**Comment by buggins** [comment]
please reopen if problem still exists
