### ISSUE TITLE
Widget's backgroundColor doesn't respect margin size

### ISSUE THREAD

**Issue by miere43** [buggins/dlangui#219]
I have got this code, as you can see button has 20px margin around it self:
```d
import dlangui;

mixin APP_ENTRY_POINT;

extern (C) int UIAppMain(string[] args) {
	Window window = Platform.instance.createWindow("D", null);
	window.mainWidget = 
		(new Button())
		.text("Test"d)
		.margins(Rect(20,20,20,20));
		
	window.show();

	return Platform.instance.enterMessageLoop();
}
```
![2016-03-24_11-49-42](https://cloud.githubusercontent.com/assets/3995549/14012518/3fe52228-f1b7-11e5-89bd-77603fa050da.png)

But when we change background color of widget color is filled without respecting margin size:
```d
import dlangui;

mixin APP_ENTRY_POINT;

extern (C) int UIAppMain(string[] args) {
	Window window = Platform.instance.createWindow("D", null);
	window.mainWidget = 
		(new Button())
		.text("Test"d)
		.backgroundColor(0xEF00EF) // <- here
		.margins(Rect(20,20,20,20));

	window.show();

	return Platform.instance.enterMessageLoop();
}
```
![2016-03-24_11-50-34](https://cloud.githubusercontent.com/assets/3995549/14012532/4fc609f0-f1b7-11e5-8db6-b1b5e0ea3afc.png)

I didn't changed window background color, but buttons color, then why is this happening? Because button is main widget? But anyway it doesn't make any sense to me.

**Comment by buggins** [comment]
Strange. Let me check...
backgroundColor must fill only content of widget + padding. It should not drawn on margins at all.

**Comment by buggins** [comment]
Removed line which redrawed button background with backgroundColor.
Now there is a problem that style (background drawable) for button is being taken for current state (not normal one). 
.backgroundColor(0xEF00EF) modifies style for normal state (State.Enabled | State.WindowFocused)
State of button in example is probably State.Enabled | State.Focused
Therefore drawable for drawing background is taken from substyle (which is not modified)

**Comment by buggins** [comment]
I hope it's closed now.
But if you want to have different background colors for different states - some more work is needed
