### ISSUE TITLE
Regression: Japanese character becomes tofu on Windows systems.

### ISSUE THREAD

**Issue by tom-tan** [buggins/dlangui#221]
On Windows systems, the following code does not show Japanese characters correctly with the latest DlangUI.

```d:
import dlangui;

immutable fontName = "Meiryo UI"; // Meiryo UI supports Japanese characters

mixin APP_ENTRY_POINT;

extern(C) int UIAppMain(string[] args)
{
    auto window = Platform.instance.createWindow("Example", null);

    auto str = "日本語"d; // the string what I want to show in the window

    auto widget = new TextWidget(null, str);
    widget.fontFace = fontName;

    window.mainWidget = widget;
    window.show;
    return Platform.instance.enterMessageLoop();
}
```

In DlangUI 0.7.75, it shows Japanese characters as intended.
<img src="https://cloud.githubusercontent.com/assets/4450141/14043679/307522fc-f2ca-11e5-9108-a969dd0ff529.png" width="320px">

However, in 0.7.76 and later, it only shows squares (tofu).
<img src="https://cloud.githubusercontent.com/assets/4450141/14043682/3803760e-f2ca-11e5-9892-2516973c5a81.png" width="320px">

On Linux systems, the above program shows Japanese characters correctly.

**Comment by buggins** [comment]
It depends on font selected.
If font does not contain some characters, squares are shown instead.

**Comment by buggins** [comment]
Fixed by disabling of FREETYPE in default configuration under Windows.

**Comment by tom-tan** [comment]
Thanks!
