### ISSUE TITLE
DlangUI IRC Client example - Can't send input

### ISSUE THREAD

**Issue by Kelet** [buggins/dlangui#248]
Hi buggins,

First of all, I'd like to express my gratitude in developing this project, and I hope it becomes a commonly-used GUI library for applications written in D. It's refreshing to see a GUI library written in D, supporting so many backends.

I'm relatively new to the D environment, so I apologize if I'm missing something obvious.

I get cloned the dlangui ~master at the time (commit 1ad136f42e97fc35e517843ffa03e05c28d14c04), and ran the IRC client example using the standard `dub run`.

It connected to the server fine, and I was able to see other people send messages. However, when I entered input, pressing the enter key would not send the input. It didn't seem to do anything. I don't see any alternative way to send input, so I'm confused as how to do so.

I'm running Windows 10 and using DMD 2.071.0, as well as DUB 0.9.24. I've tried compiling it in debug mode, release mode, and release mode with no bounds, and all of them exhibited the same behavior.

Let me know if you'd like any more information.

Regards,
Kelet

**Comment by buggins** [comment]
Probably it's broken by my recent changes
