### ISSUE TITLE
Wait for child window to close?

### ISSUE THREAD

**Issue by TheGag96** [buggins/dlangui#251]
I'm trying to implement behavior where a user clicks a button to open a new window which disables the main window and waits for newly spawned window to close before continuing just after where `someWindow.show()` was called. I've been digging through the API and haven't found what I'm looking for - is this possible given the command loop-based structure of the API?

**Comment by buggins** [comment]
It's assumed that if you create additional window which has MODAL flag, parent window should stop receiving input events. Just not yet implemented.

**Comment by buggins** [comment]
Should work fine under windows.
Not sure how about other platforms.
