### ISSUE TITLE
Class methods docs are duplicated on gh-pages

### ISSUE THREAD

**Issue by MyLittleRobo** [buggins/dlangui#255]
All method descriptions are mentioned three times.

[Example](http://buggins.github.io/dlangui/ddox/dlangui/widgets/widget/Widget.checkChange.html)

**Comment by buggins** [comment]
looks like docx issue

**Comment by MyLittleRobo** [comment]
Seems so. It happens only on Windows. Ddox on Linux generates docs without duplicates.
Filed issue to ddox repo: https://github.com/rejectedsoftware/ddox/issues/123

**Comment by MyLittleRobo** [comment]
Should be fixed in later versions. Run 'dub fetch ddox' to upgrade ddox and reupload docs on gh-pages.
