### ISSUE TITLE
StringListWidget scrollbar disappears

### ISSUE THREAD

**Issue by ifloat** [buggins/dlangui#256]
When a StringListWidget contains a lot of items the scrollbar disappears around item 106700. When trying to scroll to the very bottom, it goes back to the top after reaching a certain point.

![Scrollbar disappears](https://cloud.githubusercontent.com/assets/18277486/15005113/0fdc625c-118e-11e6-9248-626eaced4f67.gif)
![Returns to the top](https://cloud.githubusercontent.com/assets/18277486/15005114/136339e6-118e-11e6-9f9f-3cd0c301931d.gif)

**Comment by buggins** [comment]
Looks like integer overflow
