### ISSUE TITLE
Crash when mouse is in window at startup

### ISSUE THREAD

**Issue by gizmomogwai** [buggins/dlangui#259]
I have the following code (sorry for not being able to provide a minimal example):

    module app;
    
    import std.stdio;
    import std.array;
    import std.file;
    import std.path;
    import std.concurrency;
    import std.format;
    
    
    import dlangui;
    
    mixin APP_ENTRY_POINT;
    
    struct Finished {}
    
    struct Clear{}
    
    class FileInfo {
    public:
      const ulong size;
      const ulong nrOfFiles;
      this(ulong size_=0, ulong nrOfFiles_=0) {
        size = size_;
        nrOfFiles = nrOfFiles_;
      }
    
      FileInfo add(ulong size_) {
        return new FileInfo(size + size_, nrOfFiles+1);
      }
    
      override string toString() {
        return "FileInfo { nrOfFiles=%s, size=%s }".format(nrOfFiles, size);
      }
    }
    
    shared class BackgroundTask {
      Tid task;
    
      shared FileLister fileLister;
    
      string path;
    
      this(shared FileLister fileLister_, string path_) {
        fileLister = fileLister_;
        path = path_;
      }
    
      private static void runBackgroundTask(shared BackgroundTask t) {
        t.run();
      }
    
      private static void waitForBackgroundTask(shared BackgroundTask t) {
        auto child = spawn(&runBackgroundTask, t);
        while (!t.receiveMessages()) {}
      }
    
      public void start() {
        spawn(&waitForBackgroundTask, cast(shared)this);
      }
    
      public bool receiveMessages() {
        receive(
          (Finished f) {
            writeln("finished");
            return true;}
        );
        return false;
      }
    
      public abstract void run() shared;
    }
    
    class FileInfoBackgroundTask : BackgroundTask {
    
      this(shared FileLister lister, string path) {
        super(lister, path);
      }
    
      public override void run() shared {
        auto fileInfo = collectFileInfo(path);
        writeln(fileInfo);
        ownerTid.send(Finished());
      }
    
      private FileInfo collectFileInfo(string path) shared {
        auto res = new FileInfo();
        if (path.isDir()) {
          foreach (e; path.dirEntries(SpanMode.depth)) {
            if (e.isFile()) {
              res = res.add(e.getSize());
            }
          }
        } else {
          res = res.add(path.getSize());
        }
        return res;
      }
    }
    
    class FillListerBackgroundTask : BackgroundTask {
      this(shared FileLister lister, string path) {
        super(lister, path);
      }
    
      public override void run() shared {
        Clear c;
        ownerTid.send(c);
        foreach (dirEntry; dirEntries(path, SpanMode.shallow)) {
          ownerTid.send(dirEntry);
        }
        Finished f;
        ownerTid.send(f);
      }
    
      public override bool receiveMessages() {
        receive(
          (DirEntry e) {
            fileLister.add(e);
          },
          (Clear c) {
            fileLister.clear(path);
          },
          (Finished f) {
            writeln("filllister finished");
            return true;
          },
        );
        return false;
      }
    }
    
    class FileLister {
      Tid lister;
      Window window;
      ListWidget fileList;
      StringListAdapter adapter;
      string path;
      this(string path_) {
        path = path_;
        window = Platform.instance.createWindow(to!dstring("Lister: " ~ path), null);
        adapter = new StringListAdapter();
        fileList = new ListWidget("filelist", Orientation.Vertical);
        fileList.adapter = adapter;
        fileList.itemClick = delegate(Widget src, int itemIndex) {
          writeln("itemClick: ");
          return true;
        };
        fileList.click = delegate(Widget w) {
          writeln("click: ");
          return true;
        };
        fileList.keyEvent = delegate(Widget w, KeyEvent e) {
          writeln("keyEvent: ", e.action.to!string, ", ", e.keyCode.to!string, ", ", e.text);
          auto h = path ~ "/" ~ adapter.items.get((cast(ListWidget)w).selectedItemIndex).to!string;
          if (e.text == "i"d) {
            new shared(FileInfoBackgroundTask)(cast(shared)this, h).start();
          } else if (e.text == "n"d) {
            visit(h);
          } else if (e.keyCode == 8 && e.action == KeyAction.KeyUp) {
            writeln("parent dir");
            visit(dirName(path));
          }
          return true;
        };
        window.mainWidget = fileList;
        window.show();
        visit(path);
      }
    
      void visit(string path_) {
        writeln("read: ", path_);
        auto absPath = buildNormalizedPath(absolutePath(path_));
        writeln("absPath: ", absPath);
        path = absPath;
        new shared(FillListerBackgroundTask)(cast(shared)this, absPath).start();
      }
    
      void clear(string path) shared {
        (cast(Window)window).executeInUiThread(() {
            (cast(Window)window).windowCaption = path.to!dstring;
            (cast(ListWidget)fileList).selectedItemIndex = 0;
            (cast(StringListAdapter)adapter).clear();
          });
      }
    
      void add(DirEntry entry) shared {
        (cast(Window) window).executeInUiThread(delegate() {
            auto s = entry.name.baseName.to!dstring;
            if (entry.isDir) {
              s ~= "/"d;
            }
            (cast(StringListAdapter)adapter).add(s);
            (cast(Window)window).invalidate();
          });
      }
    }
    
    FileLister[string] listers;
    
    void fileLister(string[] args) {
      foreach (path; args[1..$]) {
        auto l = new FileLister(path);
        listers[path] = l;
      }
    }
    
    void spawned(TextWidget tw, Window w) {
      (cast(TextWidget)tw).executeInUiThread(delegate() {
          (cast(TextWidget)tw).text = "test1"d;
          (cast(TextWidget)tw).invalidate();
          (cast(TextWidget)w).invalidate();
        });
    }
    
    extern (C) int UIAppMain(string[] args) {
      if (args.length == 1) {
        writeln("Usage dopus dirname");
        return 1;
      }
      fileLister(args);
      return Platform.instance.enterMessageLoop();
    }

This creates a window with an initially empty list, that is filled with directory entries that are read from the filesystem in another thread. When the mouse is initially not in the window, everything is fine. When the mouse is initially on the window the application crashes with:

    2016-05-06 09:13:16.110 D  XXXXXXXXXXXXXXXXXXXXXXXXXX workaround: itemCount: 11, _itemRects: 0
    core.exception.RangeError@../dlangui/src/dlangui/widgets/lists.d(1281): Range violation
    ----------------
    4   dopus                               0x0000000103435479 _d_arraybounds + 97
    5   dopus                               0x00000001033e7cdd dlangui.widgets.lists.__array + 41
    6   dopus                               0x00000001033edc29 bool dlangui.widgets.lists.ListWidget.onMouseEvent(dlangui.core.events.MouseEvent) + 829
    7   dopus                               0x00000001033b503d bool dlangui.platforms.common.platform.Window.sendAndCheckOverride(dlangui.widgets.widget.Widget, dlangui.core.events.MouseEvent) + 141
    8   dopus                               0x00000001033b4aeb bool dlangui.platforms.common.platform.Window.dispatchMouseEvent(dlangui.widgets.widget.Widget, dlangui.core.events.MouseEvent, ref bool) + 411
    9   dopus                               0x00000001033b60c0 bool dlangui.platforms.common.platform.Window.dispatchMouseEvent(dlangui.core.events.MouseEvent) + 1672
    10  dopus                               0x00000001033bfa79 void dlangui.platforms.sdl.sdlapp.SDLWindow.processMouseEvent(dlangui.core.events.MouseAction, uint, uint, int, int) + 1153
    11  dopus                               0x00000001033c113b int dlangui.platforms.sdl.sdlapp.SDLPlatform.enterMessageLoop() + 939
    12  dopus                               0x00000001032b27a0 UIAppMain + 84
    13  dopus                               0x00000001033c1de8 int dlangui.platforms.sdl.sdlapp.sdlmain(immutable(char)[][]) + 764
    14  dopus                               0x00000001033c1ae7 DLANGUImain + 31
    15  dopus                               0x00000001032b130f _Dmain + 31
    16  dopus                               0x0000000103448c4f D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv + 39
    17  dopus                               0x0000000103448b83 void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) + 35
    18  dopus                               0x0000000103448bf4 void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() + 44
    19  dopus                               0x0000000103448b83 void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) + 35
    20  dopus                               0x0000000103448ae9 _d_run_main + 497
    21  dopus                               0x00000001032b13c9 main + 33
    22  libdyld.dylib                       0x00007fff8c9505ac start + 0
    23  ???                                 0x0000000000000001 0x0 + 1
    std.concurrency.OwnerTerminated@std/concurrency.d(237): Owner terminated
    ----------------
    4   dopus                               0x00000001032c6a4d D3std11concurrency10MessageBox69__T3getTDFS3std4file8DirEntryZvTDFS3app5ClearZvTPFNfS3app8FinishedZbZ3getMFMDFS3std4file8DirEntryZvMDFS3app5ClearZvMPFNfS3app8FinishedZbZ13onLinkDeadMsgMFKS3std11concurrency7MessageZb + 665
    5   dopus                               0x00000001032c6abd D3std11concurrency10MessageBox69__T3getTDFS3std4file8DirEntryZvTDFS3app5ClearZvTPFNfS3app8FinishedZbZ3getMFMDFS3std4file8DirEntryZvMDFS3app5ClearZvMPFNfS3app8FinishedZbZ12onControlMsgMFKS3std11concurrency7MessageZb + 41
    6   dopus                               0x00000001032c6b26 D3std11concurrency10MessageBox69__T3getTDFS3std4file8DirEntryZvTDFS3app5ClearZvTPFNfS3app8FinishedZbZ3getMFMDFS3std4file8DirEntryZvMDFS3app5ClearZvMPFNfS3app8FinishedZbZ4scanMFKS3std11concurrency36__T4ListTS3std11concurrency7MessageZ4ListZb + 98
    7   dopus                               0x00000001032c662e bool std.concurrency.MessageBox.get!(void delegate(std.file.DirEntry), void delegate(app.Clear), @safe bool function(app.Finished)*).get(scope void delegate(std.file.DirEntry), scope void delegate(app.Clear), scope @safe bool function(app.Finished)*) + 474
    8   dopus                               0x00000001032c6428 void std.concurrency.receive!(void delegate(std.file.DirEntry), void delegate(app.Clear), @safe bool function(app.Finished)*).receive(void delegate(std.file.DirEntry), void delegate(app.Clear), @safe bool function(app.Finished)*) + 172
    9   dopus                               0x00000001032b1b06 shared(bool function()) app.FillListerBackgroundTask.receiveMessages + 154
    10  dopus                               0x00000001032b158e void app.BackgroundTask.waitForBackgroundTask(shared(app.BackgroundTask)) + 42
    11  dopus                               0x00000001032bc9d7 void std.concurrency._spawn!(void function(shared(app.BackgroundTask))*, shared(app.BackgroundTask))._spawn(bool, void function(shared(app.BackgroundTask))*, shared(app.BackgroundTask)).exec() + 67
    12  dopus                               0x00000001034370ff void core.thread.Thread.run() + 43
    13  dopus                               0x00000001034369a2 thread_entryPoint + 374
    14  libsystem_pthread.dylib             0x00007fff8922199c _pthread_body + 130
    15  libsystem_pthread.dylib             0x00007fff89221919 _pthread_start + 167
    16  libsystem_pthread.dylib             0x00007fff8921f350 thread_start + 12
    17  ???                                 0xffffffffffffffff 0x0 + 18446744073709551615

i was able to workaround this by adding a sanity check to the onMouseEvent method in list.d:

        if (event.action == MouseAction.ButtonDown && (event.flags & (MouseFlag.LButton || MouseFlag.RButton)))
          setFocus();
        for (int i = 0; i < itemCount; i++) {
          if (i >= _itemRects.length) {
            Log.d("XXXXXXXXXXXXXXXXXXXXXXXXXX workaround: itemCount: ", itemCount, ", _itemRects: ", _itemRects.length);
            break;
          }
          Rect itemrc = _itemRects[i];

Am I using dlangui wrong, or is this a real bug?

**Comment by buggins** [comment]
Looks like mouse event is received before first widget painting

**Comment by buggins** [comment]
applied fix similar to your workaround.
Probably, better change could be disabling of mouse events in widgets until layout is called.

**Comment by gizmomogwai** [comment]
thanks a lot for fixing. works like a charm now (I did already try 20 days ago, but forgot to thank you!)
