### ISSUE TITLE
Action.checkAccelerator is broken

### ISSUE THREAD

**Issue by default0** [buggins/dlangui#261]
If you define an accelerator for a Ctrl+<something> hotkey, the accelerator will not work.
This is because the KeyFlag enum tracks whether the left or right control keys have been pressed and the accelerator is checked for exactly equal flags.
Since in addition to the control flag, the lcontrol  or rcontrol flags are being set, the flags are no longer equal.
So we need to special-case the key flags that have multiple meanings because otherwise the accelerators will not be matching.

**Comment by buggins** [comment]
I believe it should be fixed in v0.8.24
Distinct left and right ctrl/shift/alt/win key in accelerators should work too.
KeyFlag.LControl should work for left ctrl only, while KeyFlag.Control should work for both left and right control keys.
Please confirm if issue is fixed

**Comment by default0** [comment]
Works fine for me.

**Comment by buggins** [comment]
Great! Thank you!
