### ISSUE TITLE
Stackoverflow when assigning text in signal handler.

### ISSUE THREAD

**Issue by Kickupx** [buggins/dlangui#266]
I am trying to create a password field. So basicly I got this:

```
class PasswordEditLine : EditLine {
	this(string id) {
		super(id, "");
		this.contentChange = delegate(EditableContent src) {
			this.text = "smite";
		};
	}
}
```

After alittle of investigation I found the overflow happens in editable.d at line 754.
Snippet:

```
else {
            _lines.length = 1;
            _lines[0] = replaceEolsWithSpaces(newContent);
            _tokenProps.length = 1;
            updateTokenProps(0, cast(int)_lines.length);
}
```

where the _lines[0] assignment is causing the overflow.
I am compiling to windows x86.

UPDATE:
Never mind. I just came to realize this causes an infinite loop.

**Comment by buggins** [comment]
Closing issue like not a bug, just misuse

**Comment by default0** [comment]
Would make sense to check if theres an appropriate spot in the documentation to mention that you cannot do that, since it isn't necessarily obvious to everyone.
