### ISSUE TITLE
chaining setters looses exact Widget type

### ISSUE THREAD

**Issue by gizmomogwai** [buggins/dlangui#268]
I would like to chain some setters together with the initialization, e.g.:

````d
auto vl = new VerticalLayout("vl").layoutWidth(FILL_PARENT).layoutHeight(FILL_PARENT);
````

Problem is, that vl now is of type widget, as layoutWidth and layoutHeight are inherited from Widget and return this (a Widget).
It would be great if there is a clever d-trick to let them return the correct subtype.

As a workaround the two liner:
`````
d
auto vl = new VerticalLayout("vl");
vl.layoutWidth(FILL_PARENT).layoutHeight(FILL_PARENT);
````
always works, but it still would be nice.

**Comment by buggins** [comment]
not sure how to do it

**Comment by buggins** [comment]
trick: use DML for creation of layouts.
Below is equivalent of your code:

```
//import dlangui.dml.parser;
//import dlangui.widgets.layouts;
auto vl = parseML!VerticalLayout(q{ VerticalLayout { layoutWidth: fill; layoutHeight: fill }  });

```

**Comment by gizmomogwai** [comment]
nice. thanks ... i will give this a try. i also do not see a way to do this with d-lang tools.
