### ISSUE TITLE
Provide a standalone Editor similar to SublimeText/NotePad++/GVim/Atom

### ISSUE THREAD

**Issue by zhaopuming** [buggins/dlangui#273]
This will be a good showcase for dlangui, complementing dlangide.

Editors are much more flexible than a full IDE, and it could be used more generally, for one-shot plain text editing and other languages (if you provide a plugin system).

**Comment by GrimMaple** [comment]
As goals of this project might have shifted, I don't think this is going to be done in this project. If anyone wants to do that somewhere else - please, do so :)
