### ISSUE TITLE
Forum dedicated to dlangui

### ISSUE THREAD

**Issue by zhaopuming** [buggins/dlangui#274]
I've just started using dlangui to develop a GUI for our internal use, which mainly involves real time charting. I guess there will be many questions I want to ask about the details of dlangui. But there is no GUI/dlangui specific forum in forum.dlang.org, and asking many questions here is also not appropriate here is for issues. So I suggest that you setup a forum for dlangui related questions? It's similar to the dub/vibe.d forum in vibed.org.

**Comment by buggins** [comment]
There is a Gitter chat
https://gitter.im/buggins/dlangide
(chat button on project page)

**Comment by buggins** [comment]
freenet IRC channel #DlangUI

**Comment by zhaopuming** [comment]
Thanks ~

**Comment by buggins** [comment]
There was an idea to rename DWT forum to GUI.
IMHO it would allow to discuss DlangUI and other libraries on dlang.org forum
