### ISSUE TITLE
drawCircle and other shapes in DrawBuf

### ISSUE THREAD

**Issue by zhaopuming** [buggins/dlangui#276]
Can you provide more draw shape and fill shape methods in DrawBuf?
- polygon
- circle
- ellipse
- bezier

etc

**Comment by buggins** [comment]
Is it ok to draw it using line of single pixel width

**Comment by zhaopuming** [comment]
I don't know enough about OpenGL or SDL, do they provide these functions? Otherwise we might need to draw it pixel by pixel.

**Comment by buggins** [comment]
Implemented.
Added functions fillEllipse, drawPoly, polyLine, fillTriangle, etc...
