### ISSUE TITLE
Need way to set window size/options

### ISSUE THREAD

**Issue by Gibbz** [buggins/dlangui#280]
Hey, ive just started using this library. I see no way to set a window size.
Is there any way to go about setting the size of my windows in pixels? 
If not can support be added in for it?

Thanks

**Comment by buggins** [comment]
partially implemented - window.setWindowState()
implemented for Windows platform only so far

**Comment by buggins** [comment]
#258

**Comment by buggins** [comment]
Assuming it's working.
