### ISSUE TITLE
Password field

### ISSUE THREAD

**Issue by WebFreak001** [buggins/dlangui#282]
Is there anything for entering passwords? Or a field in EditLine which allows to mask the characters?

If not, it would be really nice having it for launchers or login forms or other usecases where you need to hide the input

**Comment by buggins** [comment]
I don't remember. Via quick search, I did not found this feature.
Assuming it's to be done.

**Comment by buggins** [comment]
// use passwordChar property of EditLine
editLine.passwordChar = '*'; // password editor
editLine.passwordChar = 0; // normal editor
