### ISSUE TITLE
Changing CheckBox -> CheckButton

### ISSUE THREAD

**Issue by laberba** [buggins/dlangui#287]
Since other button widgets are all *Button, I believe making this change will improve consistency in naming conventions.

**Comment by buggins** [comment]
Probably it makes sense. But would create incompatibility.
Working solution - create an alias.

**Comment by laberba** [comment]
Why not make it built in and add a depreciation message for users to switch before its too late.

**Comment by bfloch** [comment]
The reason for loose naming is you never know what the parent class might be in future. Imagine an intermediate "State" class is added for all state-like widgets like the checkbox (silly example). Would it be worth to rename it?

It's better name things according to their purpose not implementation.
Technically "checkbox" seems to be correct: https://en.wikipedia.org/wiki/Checkbox

This quickly becomes a question of preference:
fltk/gtk/... ~ checkbutton
winform/qt/... ~ checkbox

**Comment by buggins** [comment]
In many other GUI libs this control is called CheckBox, too
Probably, we can leave its name as is

**Comment by buggins** [comment]
I prefer CheckBox. Closing.
