### ISSUE TITLE
Why not merget these widgets ...

### ISSUE THREAD

**Issue by laberba** [buggins/dlangui#288]
Currently we have `VSpacer` and `HSpacer` which all does basically the same things except for how they layout widgets, why not merge them so that the user can explicitly indicate the layout with an `enum` or something like `Orientation.Vertical`?

Same thing for `VerticalLayout` and `HorizontalLayout`

**Comment by buggins** [comment]
It's just for convenience.
E.g. you can add new VSpacer() w/o setting extra orientation parameter

**Comment by laberba** [comment]
That mskes too many widgets to maintain. It doesn't take much tine to write an enum to specify orientation.
