### ISSUE TITLE
Can't build on Windows

### ISSUE THREAD

**Issue by IceNature** [buggins/dlangui#29]
Use dmd 2.066.1.
The error message like this:
>Building dlib ~master configuration "library", build type release.
>Running dmd...
>AppData\Roaming\dub\packages\dlib-master\dlib\filesystem\windows\directory.d(77)
>: Error: std.string.wcslen at E:\DeveloperTools\dmd2\dmd2\windows\bin\..\..\src\phobos\std\string.d(42) conflicts with core.stdc.wchar_.wcslen at E:\DeveloperTools\dmd2\dmd2\windows\bin\..\..\src\druntime\import\core\stdc\wchar_.d(102)FAIL AppData\Roaming\dub\packages\dlib-master\.dub\build\library-release-windows-x86-dmd_2066-1B722BF4E0DEE69FE2B7DDC21C62E24B\ dlib staticLibrary
>Error executing command run: dmd failed with exit code 1.

**Comment by XuTpuK** [comment]
+Bug: title page missed one more dependency: https://github.com/DerelictOrg/DerelictFI.git

**Comment by buggins** [comment]
Looks like dlib issue.

**Comment by buggins** [comment]
probably fixed - changed dlib dependency from ~master to >=0.4.1
