### ISSUE TITLE
[Xp32] dlangui fails on EnumFontFamiliesExA

### ISSUE THREAD

**Issue by UplinkCoder** [buggins/dlangui#294]
as per tile.
It segfaults in Win32FontManager.initialize()

**Comment by buggins** [comment]
Documentation sais, EnumFontFamiliesExA should work since Win2K.
It looks like I have to install XP in virtual box to fix it.

**Comment by buggins** [comment]
Reproduced on Win7, too.
Probably it has been broken by changing custom win32 api implementation to one from DRuntime.

**Comment by buggins** [comment]
Fixed.
Thank you for reporting this issue!
