### ISSUE TITLE
How to debug on Visual-D

### ISSUE THREAD

**Issue by ghostwheel** [buggins/dlangui#299]
I installed dlangui under visual studio community 2013.
I download the gui and all deps, under the directory deps.
When I compile for "Debug" all seems well, and the example programs run. 
However, when I try to debug by setting a breakpoint and select "Start debugging", I get an error message:

cannot launch debugger on 
C:\work\dgui\dlangui\Debug\dlangui.lib 
hr=89710016

**Comment by buggins** [comment]
Did you install visualD with mago debugger?
In project settings / debugger, try to select "mago".

**Comment by buggins** [comment]
BTW, you can fetch submodules in deps by simple git pull --recurse-submodules

**Comment by ghostwheel** [comment]
> On 05 Oct 2016, at 0:29 , Vadim Lopatin <notifications@github.com> wrote:
> Did you install visualD with mago debugger?
> In project settings / debugger, try to select "mago".
> 
OK, I installed Visual Studio community 2015, to check if that is the problem. It isn’t.
I also installed 3.44 beta 1

It took me a long time to find the setting. I couldn’t find it in project setting.
Instead, I modified: menu Tools->Options
Projects and solutions -> Visual D settings
There I chose Debugger: Mago.

Same error. I have a feeling that choosing Mago didn’t actually do anything…

**Comment by ghostwheel** [comment]
> On 05 Oct 2016, at 0:30 , Vadim Lopatin <notifications@github.com> wrote:
> 
> BTW, you can fetch submodules in deps by simple git pull --recurse-submodules
> 
> 
Didn’t work for me. I cd-ed into dlangui, executed the above command, and git said its done.
I had to cd into deps and do:
    git clone https://github.com/DerelictOrg/DerelictUtil.git
    git clone https://github.com/DerelictOrg/DerelictGL3.git
    git clone https://github.com/DerelictOrg/DerelictFI.git
    git clone https://github.com/DerelictOrg/DerelictFT.git
    git clone https://github.com/DerelictOrg/DerelictSDL2.git

**Comment by ghostwheel** [comment]
I finally managed to figure out how to configure the project. Once you know it it is so easy. I was clicking on a source file, and on the total solution to try to look at properties, instead of on the "folder" (i.e. the project).
I tried various options, with and without Mago, with cv2pdb and without, and all gave the same error.
I did see that using Mago is different from Visual Studio debugger in that I get an additional error with the visual studio debugger:
Collector agent (ID: NativeMemoryCollectionAgent.dll) is not a known agent.

When I select 'Start without debugging' nothing seems to happen. I can start the program 
directly from the .exe file, and then the dialog (for the helloworld example) comes up.
I can attach to the running process, but then breakpoints don't seem to work. I can pause and resume the process, but never manage to capture it in the actual source window.

**Comment by buggins** [comment]
Instruction for cloning deps separately is outdated. git clone dlangui --recurse-submodules to be used instead.

**Comment by buggins** [comment]
cannot launch debugger on
C:\work\dgui\dlangui\Debug\dlangui.lib
hr=89710016

You are trying to run library.
Instead, you have to select some executable project as startup project.
E.g. right click on example1 project and choose "Set as startup project" from context menu.
Once it's done, VisualD will run example1.exe when trying to Debug/Start Debugging

**Comment by buggins** [comment]
Please let me know if I can close this issue

**Comment by default0** [comment]
imho would be cleaner to detect if user is trying to launch library and display error message stating the issue.

**Comment by buggins** [comment]
makes sense

**Comment by ghostwheel** [comment]
Thank you, that worked!

Michael

**Comment by buggins** [comment]
Closing issue
