### ISSUE TITLE
Segmentation fault on exit

### ISSUE THREAD

**Issue by FreeSlave** [buggins/dlangui#302]
Running example1 on Linux. Exiting via menu 'Exit' entry or via cross button on title bar leads to segmentation fault.

Running in gdb gives 
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000007362d8 in dlangui.core.types.__T3RefTC7dlangui8graphics7drawbuf7DrawBufZ.Ref.clear() (this=...) at src/dlangui/core/types.d:452
452                 _data.releaseRef();
```

**Comment by buggins** [comment]
reproduced on Windows build in SDL config after adding Runtime.terminate();

**Comment by buggins** [comment]
should be fixed in 0.9.20
Please confirm - I tested it on Windows

**Comment by FreeSlave** [comment]
Yes, it's ok now.

**Comment by buggins** [comment]
Thank you!
Closing issue.
