### ISSUE TITLE
Progress Bar doesn't seem to render in Console mode

### ISSUE THREAD

**Issue by tslater2006** [buggins/dlangui#309]
I have a progress bar placed on the status line of an AppFrame. It looks great in the UI version but when built with "console" configuration for dlangui it doesn't show up.

UI Build:
![image](https://cloud.githubusercontent.com/assets/1731714/19455133/86270798-9481-11e6-8b5e-73c4dc346875.png)

Console Build:
![image](https://cloud.githubusercontent.com/assets/1731714/19455105/655fee58-9481-11e6-97c3-89ce8f14574c.png)

**Comment by buggins** [comment]
Need to fix console theme and probably progressbar drawing code

**Comment by buggins** [comment]
Fixed progress bar, switch button, group box, slider, grid for console mode.
Let me know if current progress bar look & feel is ok.

**Comment by tslater2006** [comment]
thanks for such a quick turnaround on this. Here's how it looks now:

![image](https://cloud.githubusercontent.com/assets/1731714/19483235/4f86b722-9519-11e6-8908-56b22375cc80.png)

While this works I feel the gray on top of the blue is a bit strange, could it possibly just be a solid blue? Merely a suggestion. It certainly works as-is and I thank you for such a quick fix.

**Comment by buggins** [comment]
It should be grey squares ■, Probably, due to font, there is no space between squares. 
Fix is simple - one character in console_theme_default.xml
    <style id="PROGRESS_BAR"
        minWidth="10"
        minHeight="1"
        backgroundImageId="{'░' 0x808000 stretch}"
        >
        <drawable id="progress_bar_gauge" value="{'■' 0x808080 bc 0x0000FF stretch}"/>
        <drawable id="progress_bar_gauge_animation" value="@none"/>
        <drawable id="progress_bar_indeterminate" value="{'░' 0x808000 stretch}"/>
        <drawable id="progress_bar_indeterminate_animation" value="@none"/>
    </style>


Do you think solid blue is ok? Maybe, vertical line is better? '│'

**Comment by buggins** [comment]
Submitted solid blue progress gauge so far.

**Comment by tslater2006** [comment]
Looks a lot better to me! Thanks for such quick turnaround on this.
