### ISSUE TITLE
FileDialog folder drill-in not working in console mode

### ISSUE THREAD

**Issue by tslater2006** [buggins/dlangui#310]
When creating a FileDialog, it seems I'm unable to drill into the folders via double click when in console mode. There is no other apparent way to navigate through folders.

![image](https://cloud.githubusercontent.com/assets/1731714/19531159/43301534-95fc-11e6-8319-f13f55c2c671.png)

**Comment by tslater2006** [comment]
You can close this if you'd like. I just figured out I can press Enter to step into a folder so its workable for now :)

**Comment by buggins** [comment]
Probably double click detection is not implemented for console. Let me check.
Enter and Space should work both.

**Comment by buggins** [comment]
Fixed mouse double click in console mode.
