### ISSUE TITLE
Regression (Windows): winapp.d(1273,61): Error: no property 'instanceCount'

### ISSUE THREAD

**Issue by tom-tan** [buggins/dlangui#314]
The following code can not be compiled in release mode on Windows systems.
This issue occurs when I use DlangUI 0.9.22 or later.

By using debug mode, it can be compiled successfully.
On Linux and Mac systems, this code can be compiled successfully in debug and release mode.

```
import dlangui;

void main(string[] args)
{
}
```

Actual output:
```
dub build -b release
(snip)
..\..\Users\appveyor\AppData\Roaming\dub\packages\dlangui-0.9.40\dlangui\src\dlangui\platforms\windows\winapp.d(1273,61): Error: no property 'instanceCount' for type 'dlangui.graphics.drawbuf.DrawBuf'
```

**Comment by buggins** [comment]
Fixed. Thank you!
