### ISSUE TITLE
Cannot be compiled on Windows 64bit systems with dmd 2.072.1

### ISSUE THREAD

**Issue by tom-tan** [buggins/dlangui#319]
DlangUI 0.9.46 cannot be compiled on Windows 64bit systems with dmd 2.0.72.1.
It can be compiled on Windows 32bit and Linux systems.
When I use dmd 2.071.1, it can be compiled without errors.

## How to reproduce: 
- `dub init sample dlangui`
- Use the following `app.d`:

```d:
import dlangui;

mixin APP_ENTRY_POINT;

extern(C) int UIAppMain(string[] args)
{
    return 0;
}
```
- `dub build`

## Expected
The above code can be compiled without errors.

## Actual
The build fails with the following errors:
```
uuid.lib(shguids.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
fatal error C1905: Front end and back end not compatible (must target same processor).
LINK : fatal error LNK1257: code generation failed
Error: linker exited with status 16990832
```

**Comment by buggins** [comment]
Does this issue still exist with latest DMD?

**Comment by and3md** [comment]
Works for me. Issue should be closed. 
Tested on Windows 7 64bit with dlangui 0.9.57, and dmd 2.074.0 (VS 2013u4) subconfiguration `sdl`, `default` (`dub --force run -a=x86` for 32bit, and  `dub --force run -a=x86_64` for 64bit).

**Comment by tom-tan** [comment]
I confirmed it still fails on Windows 64bit systems in AppVeyor...

Here are the status in AppVeyor and source code.
AppVeyor status: https://ci.appveyor.com/project/tom-tan/sample
Source: https://github.com/tom-tan/sample

**Comment by buggins** [comment]
Do other D apps work ok in AppVeyor?

**Comment by tom-tan** [comment]
For example, [vibe.d](http://vibed.org/) uses AppVeyor and
it passes CI tester with dmd 2.073.1.

Link: https://ci.appveyor.com/project/s-ludwig/vibe-d

**Comment by buggins** [comment]
checked on win7 x64  + dub 1.0.0 + dmd 2.0.75 - compiles ok

**Comment by tom-tan** [comment]
I confirmed the above code can be successfully compiled with dlangui 0.9.87 on the following combinations.
Note that we have to set `Visual Studio 2017` image instead of `Visual Studio 2015` image (it is a default image for AppVeyor) in `appveyor.yml`.

- Build platform:
  - Windows Server 2016 (64bit OS: used in AppVeyor `Visual Studio 2017` image)

- Target platform:
  - Windows 32bit
  - Windows 64bit

- Compiler:
  - dmd 2.072.0
  - dmd 2.075.0
  - ldc 1.3.0

Thanks a lot!
