### ISSUE TITLE
Trying to run library, getting errors

### ISSUE THREAD

**Issue by MatthewFrench** [buggins/dlangui#33]
src/dlangui/core/linestream.d(141): Error: cannot implicitly convert expression (encode(d, s[cast(ulong)i])) of type ulong to int
src/dlangui/core/linestream.d(149): Error: cannot implicitly convert expression (encode(d, s[cast(ulong)i])) of type ulong to int
src/dlangui/core/linestream.d(159): Error: cannot implicitly convert expression (encode(d, s[cast(ulong)i])) of type ulong to int
src/dlangui/widgets/editors.d(489): Error: function dlangui.widgets.editors.EditableContent.updateTokenProps (int startLine, int endLine) is not callable using argument types (int, ulong)
src/dlangui/widgets/editors.d(537): Error: function dlangui.widgets.editors.EditableContent.lineEnd (int lineIndex) is not callable using argument types (ulong)
src/dlangui/widgets/editors.d(578): Error: function dlangui.widgets.editors.EditableContent.updateTokenProps (int startLine, int endLine) is not callable using argument types (int, ulong)
src/dlangui/widgets/editors.d(583): Error: function dlangui.widgets.editors.EditableContent.updateTokenProps (int startLine, int endLine) is not callable using argument types (int, ulong)
FAIL .dub/build/library-release-posix.osx-x86_64-dmd_2066-5B9F27E2A8B1C082EF974C9AAA016B0E/ dlanguilib staticLibrary
Error executing command run: dmd failed with exit code 1.

**Comment by drug007** [comment]
This happens because you build 64 bit.
@buggins why you use int instead of size_t for length? Is it intended so or "так исторически сложилось"?

**Comment by buggins** [comment]
fixed today
