### ISSUE TITLE
dml docs

### ISSUE THREAD

**Issue by John-Colvin** [buggins/dlangui#345]
There doesn't appear to be any documentation of `dml` itself. As far as I can tell it matches one-to-one with the class types (and their members) in `dlangui`, is that true?

**Comment by and3md** [comment]
I don't know this part of sources too good so let someone correct me if I'm wrong.

Widgets that are available for DML are registered in startup code:
https://github.com/buggins/dlangui/blob/master/src/dlangui/platforms/common/startup.d#L321

How they are registered you can see here:
https://github.com/buggins/dlangui/blob/master/src/dlangui/widgets/metadata.d

Which properties are available depends on SetXXXXXProperty() methods.
For example see widget.d file:
https://github.com/buggins/dlangui/blob/master/src/dlangui/widgets/widget.d#L1607

**Comment by buggins** [comment]
Docs will be added on Wiki
https://github.com/buggins/dlangui/wiki/Using-DML-to-create-layouts

**Comment by buggins** [comment]
I suppose current state of docs on Wiki is good enough.
Closing this issue.
If something is unclear, please submit your questions as a separate issue.
