### ISSUE TITLE
Oddly high CPU usage 

### ISSUE THREAD

**Issue by TheGag96** [buggins/dlangui#347]
Clicking between elements in a pretty basic program will often cause a pretty high CPU and memory spike, even there aren't any handlers for those actions. I'm on Windows 8.1 x64, i5-750. A fairly old CPU, but it probably shouldn't be working this hard. This happens even if I use --build=release.

https://gfycat.com/ThatHardAsianpiedstarling

This can't be normal, can it?

**Comment by and3md** [comment]
Which platform are you using? `SDLPlatform`, `Win32Platform`?
Is OpenGL context created or software drawing?
Do you have the same problem in other dlangui apps?

I don't have windows 8.1 but I make some test on Windows 7 and Linux using my own project:

On Windows 7 x64 i5-3550
- `Win32Platform` - idle 2% cpu, when clicking all the time - 5%
- `SDLPlatform` - idle 3-5%, when clicking 8%-10%

On linux:
- `SDLPlatform` - idle 1-2%, when clicking 2%-3%

**Comment by TheGag96** [comment]
Am I choosing these platforms correctly? I've tried `subConfigurations "dlangui" "sdl"` and `subConfigurations "dlangui" "minimal"` in my dub.sdl, and performance seems the same for both. I tried --build=release again, it does seem to cut the max CPU usage doing what I showed in the video from ~16% to ~10%.

I do not make any OpenGL contexts explicitly, so I assume it's just doing software rendering by default?

**Comment by and3md** [comment]
On windows dlangui try create OpenGL context automatically in `default` and `sdl` sub configuration. You can check that in ui.log there should be line:
> OpenGL is initialized ok

`minimal` sub config do not use OpenGL.

What sub config you use you can see during compilation something like:
> dlangui 0.9.56: target for configuration "default" is up to date

What graphics card do you have?

**Comment by TheGag96** [comment]
I have an nVidia GTX 770 (2 GB).

**Comment by and3md** [comment]
I can reproduce the issue when moving cursor all the time over menu items. The highest CPU usage I report in theme menu in example1 (22%) but moving selection by keyboard only 11%. So most likely there is something in mouse over code in menu.

**Comment by and3md** [comment]
Please check #350 and #351 fix it for you. #350 fixes high CPU usage in example1 (22%) for me now 3-8%, 
If you have you own widgets with `onDraw()` check it sets `_needDraw` to `false`.
