### ISSUE TITLE
Written guide on theming

### ISSUE THREAD

**Issue by aberba** [buggins/dlangui#353]
I've always wanted to develop a theme but seems the readme suggest that you know android theming. Could you write a small guide on the theming process and icon size specifics?

**Comment by buggins** [comment]
First part: Added tutorial about resources on Wiki

**Comment by aberba** [comment]
Awesome. I will check it out and give you feedback later

**Comment by buggins** [comment]
Updated.
Please let me know if something is not clear.

**Comment by buggins** [comment]
Mostly ready. Sample source code can be found in dlangui/examples/themetest/

**Comment by buggins** [comment]
Closing this issue.
If something is unclear in docs, please submit additional issue.
