### ISSUE TITLE
File dialog always raises above windows of other applications

### ISSUE THREAD

**Issue by FreeSlave** [buggins/dlangui#355]
On Linux run example1 and open file dialog. Try to move window of some other application upon dlangui file dialog. File dialog will always raise.

**Comment by and3md** [comment]
I can't reproduce it on linux Mint with Cinnamon, or Sparky with XFCE. What desktop environment do you use?

**Comment by FreeSlave** [comment]
It happens on LXDE.

**Comment by buggins** [comment]
Probably, it's behavior of SDL_RaiseWindow in LXDE.
sdlapp.d:359
        SDL_RaiseWindow(_win);

**Comment by FreeSlave** [comment]
I found that it's enough to drag the other window upon the main example1 window in presence of file dialog.

**Comment by and3md** [comment]
Current modal window behavior implementation in SDL app works by rising/minimizing modal child windows on some events. One of this event is window focus gain. I suspect that in your environment mouse cursor automatically focus windows under it. Am I right?

**Comment by FreeSlave** [comment]
No, windows don't get focused just by mouse hovering in my environment, I usually need to explicitly click.
Here's video of how it happens.
[out.ogv.zip](https://github.com/buggins/dlangui/files/1039402/out.ogv.zip)

**Comment by and3md** [comment]
Ok, I can reproduce the issue. Working on solution ;)
