### ISSUE TITLE
UNTRANSLATED and UIString in interfaces

### ISSUE THREAD

**Issue by FreeSlave** [buggins/dlangui#361]
dlangui puts this in UIStrings which are not translated.
But what if I need to show arbitrary text that comes from other source? UIString in interfaces prevents me from doing this without this "UNTRANSLATED" prefix.
E.g. I want to show OS error in message box, but it uses UIString for message. I can't know all messages that may come from OS and actually they may come already translated (e.g. by libc).

Usage of translations should be optional, not forced.

**Comment by FreeSlave** [comment]
Ok I got it. If UIString is constructed from char string, this char string considered to be id. If it's constructed from dstring, then it's raw text.
I think constructors with different meaning depending on encoding is bad design. Would be better to have UIString created as raw text from string. For id-based strings UIString can have static method like UIString.fromId or UIString.localized. This also would make it explicit.

**Comment by buggins** [comment]
Added UIString.fromId() and UIString.fromRaw().
I think deprecating of constructors would be inconvenient.

**Comment by FreeSlave** [comment]
Deprecating would help to find all usages of constructors in the library code itself.

**Comment by FreeSlave** [comment]
Also would be useful to have fromRaw overload that takes string, not dstring. Just to be compatible with phobos and other libraries that mostly use char string.
By the way can you explain the reasoning behind storing all gui strings as dstring?

**Comment by buggins** [comment]
Don't deprecated method calls cause failed build by default?

**Comment by buggins** [comment]
added fromRaw(string) overload

**Comment by FreeSlave** [comment]
Deprecation is just a warning unless you use -de flag.

**Comment by buggins** [comment]
Done. I just hope nothing will break after this change.
