### ISSUE TITLE
PopupMenu outside window

### ISSUE THREAD

**Issue by vitalfadeev** [buggins/dlangui#378]
Доброго дня!
Может ли PopupMenu отображаться за пределами окна?

Например,
у меня SDL-окно 1366x48,
в окне кнопка ImageButton
при клике на кнопку желаю открыть меню. 
(как кнопка Пуск в windows)
Оно выходит, но в сжатом виде. Догадываюсь почему.
Вот так: 
![image](https://s3.postimg.org/a5sbttmyp/2017-06-22-201936_1366x77_scrot.png?dl=1)

Желаю сделать панель с кнопкой "Пуск". Как в LXDE. 
Вот как здесь:
![menu](https://upload.wikimedia.org/wikipedia/commons/c/cd/Lxpanel_menu.png)

Сейчас мысль - сделать созданием второго окна, с выводом PopupMenu в нем.
Как проще и легче?

**Comment by FreeSlave** [comment]
Если создавать отдельное окно для меню, то его нужно создавать без декораций.
В SDL2 можно создавать окно с флагом SDL_WINDOW_POPUP_MENU, но только начиная с версии 2.05.

**Comment by buggins** [comment]
Сейчас так нельзя. Сделать довольно сложно.

**Comment by buggins** [comment]
Сейчас так нельзя. Сделать довольно сложно.

**Comment by FreeSlave** [comment]
Кстати, то же самое касается тултипов.
А меню как окна всё равно придется делать ещё и для иконки в трее.
