### ISSUE TITLE
failure on access of CD-ROM

### ISSUE THREAD

**Issue by bubnenkoff** [buggins/dlangui#38]
If i click on CD-Device that have not disk in шею I am getting error:

"---------------------------
Error
---------------------------
std.file.FileException@std\file.d(919): E:\: Устройство не готово.
----------------
0x0040DF38 in pure @safe bool std.exception.enforce!(bool).enforce(bool, lazy object.Throwable) at C:\D\dmd2\windows\bin\..\..\src\phobos\std\exception.d(498)
0x004CBD6C in uint std.file.getAttributes(const(char[]))
0x0046236B in bool dlangui.dialogs.filedlg.FileDialog.openDirectory(immutable(char)[], immutable(char)[]) at C:\Users\bubenkov_di\Downloads\dcd\dlangide-master\dlangide-master\..\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\dialogs\filedlg.d(150)
0x00462CFB in D7dlangui7dialogs7filedlg10FileDialog15createRootsListMFZ12__dgliteral1MFC7dlangui7widgets6widget6WidgetiZb at C:\Users\bubenkov_di\Downloads\dcd\dlangide-master\dlangide-master\..\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\dialogs\filedlg.d(245)
0x0047A2DA in D7dlangui4core7signals58__T6SignalTC7dlangui7widgets5lists21OnItemSelectedHandlerZ6Signal4emitMFC7dlangui7widgets6widget6WidgetiZ14__foreachbody4MFKDFC7dlangui7widgets6widget6WidgetiZbZi at C:\Users\bubenkov_di\Downloads\dcd\dlangide-master\dlangide-master\..\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\core\signals.d(215)
0x0047A9F5 in int dlangui.core.collections.Collection!(bool delegate(dlangui.widgets.widget.Widget, int), false).Collection.opApply(int delegate(ref bool delegate(dlangui.widgets.widget.Widget, int))) at C:\Users\bubenkov_di\Downloads\dcd\dlangide-master\dlangide-master\..\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\core\collections.d(158)
0x0047A29C in bool dlangui.core.signals.Signal!(dlangui.widgets.lists.OnItemSelectedHandler).Signal.emit(dlangui.widgets.widget.Widget, int) at C:\Users\bubenkov_di\Downloads\dcd\dlangide-master\dlangide-master\..\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\core\signals.d(214)
0x0047A254 in bool dlangui.core.signals.Signal!(dlangui.widgets.lists.OnItemSelectedHandler).Signal.opCall(dlangui.widgets.widget.Widget, int) at C:\Users\bubenkov_di\Downloads\dcd\dlangide-master\dlangide-master\..\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\core\signals.d(211)
0x004787BA in void dlangui.widgets.lists.ListWidget.itemClicked(int) at C:\Users\bubenkov_di\Downloads\dcd\dlangide-master\dlangide-master\..\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\widgets\lists.d(342)
0x0047A0E7 in bool dlangui.widgets.lists.ListWidget.onMouseEvent(dlangui.core.events.MouseEvent) at C:\Users\bubenkov_di\Downloads\dcd\dlangide-master\dlangide-master\..\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\widgets\lists.d(865)
0x0049CF97 in bool dlangui.platforms.common.platform.Window.sendAndCheckOverride(dlangui.widgets.widget.Widget, dlangui.core.events.MouseEvent) at C:\Users\bubenkov_di\Downloads\dcd\dlangide-master\dlangide-master\..\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\platforms\common\platform.d(504)
0x0049D6C3 in bool dlangui.platforms.common.platform.Window.dispatchMouseEvent(dlangui.core.events.MouseEvent) at C:\Users\bubenkov_di\Downloads\dcd\dlangide-master\dlangide-master\..\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\platforms\common\platform.d(676)
0x004A0E71 in bool dlangui.platforms.windows.winapp.Win32Window.onMouse(uint, uint, short, short) at C:\Users\bubenkov_di\Downloads\dcd\dlangide-master\dlangide-master\..\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\platforms\windows\winapp.d(597)
0x0049FF45 in WndProc at C:\Users\bubenkov_di\Downloads\dcd\dlangide-master\dlangide-master\..\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\platforms\windows\winapp.d(1034)
0x768362FA in gapfnScSendMessage
0x76836D3A in GetThreadDesktop
0x768377C4 in CharPrevW
0x7683788A in DispatchMessageW
0x0048D011 in int dlangui.platforms.windows.winapp.Win32Platform.enterMessageLoop() at C:\Users\bubenkov_di\Downloads\dcd\dlangide-master\dlangide-master\..\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\platforms\windows\winapp.d(694)
0x0043675C in UIAppMain at C:\Users\bubenkov_di\Downloads\dcd\dlangide-master\dlangide-master\src\dlangide.d(48)
0x00467E80 in int dlangui.platforms.windows.winapp.myWinMain(void*, void*, char*, int) at C:\Users\bubenkov_di\Downloads\dcd\dlangide-master\dlangide-master\..\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\platforms\windows\winapp.d(943)
0x004452C0 in DLANGUIWinMain at C:\Users\bubenkov_di\Downloads\dcd\dlangide-master\dlangide-master\..\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\platforms\windows\winapp.d(807)
0x00436662 in WinMain at C:\Users\bubenkov_di\Downloads\dcd\dlangide-master\dlangide-master\..\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\platforms\common\platform.d(946)
0x00502712 in WinMainCRTStartup
0x75FA338A in BaseThreadInitThunk
0x76F39F72 in RtlInitializeExceptionChain
0x76F39F45 in RtlInitializeExceptionChain
---------------------------
ОК   
---------------------------"

**Comment by buggins** [comment]
Does this issue still exist? I have no access to CDROM
