### ISSUE TITLE
Please provide API for external platform implementation

### ISSUE THREAD

**Issue by denizzzka** [buggins/dlangui#386]
For example, I am want to implement BearLibTerminal target (https://github.com/Elronnd/bearlibterminal-dlang), but I am sure what here is too small potential users of these target.

**Comment by denizzzka** [comment]
Currently I am trying to do this job:
https://github.com/denizzzka/dlangui/tree/external_target

**Comment by buggins** [comment]
Your pull request is merged.
Can we close this issue?

BTW, is bearlibterminal better than internal terminal support implementation in DlangUI?

**Comment by buggins** [comment]
PR is merged. Closing.

**Comment by denizzzka** [comment]
> BTW, is bearlibterminal better than internal terminal support implementation in DlangUI?

It is another thing: BearLib terminal actually is graphical window what emulates console for nostalgy purposes.
![](http://d2.alternativeto.net/dist/s/bearlibterminal_782613_full.png?format=jpg&width=1600&height=1600&mode=min&upscale=false)
