### ISSUE TITLE
Explanation about of _textSizeBuffer ?

### ISSUE THREAD

**Issue by denizzzka** [buggins/dlangui#387]
```D
protected int[] _textSizeBuffer; // buffer to reuse while measuring strings - to avoid GC
```
Can anyone explain exactly that stored in this array? The code around this array is not obvious (in my opinion).

This is important for new platforms implementation.

**Comment by and3md** [comment]
This array store character widths - cumulatively so:
(n + 1) character width in array = (n characters width) + ((n+1) character width). 

See: `Font.measureText()`

**Comment by denizzzka** [comment]
And this array used only for each one text string?

**Comment by and3md** [comment]
I think `textSize()` function use it to speed-up text measuring (array is created only once not in every `textSize()` call). `textSize()` returns Point so this is only for internal use.

**Comment by and3md** [comment]
drawText() and drawColoredText() use it too.

**Comment by denizzzka** [comment]
> textSize() returns Point so this is only for internal use.

I am write my own `measureText` thus I am need to use this buffer by right way

**Comment by denizzzka** [comment]
> This array store character widths - cumulatively

So, after monospaced line 'abc def' is measured _textSizeBuffer will contain something like:
`[10, 10, 10, 10, 10, 10, 10]` where 10 is width of each letter?

**Comment by and3md** [comment]
`Font.measureText()` not uses this buffer, but functions that use `Font.measureText()` use it (`textSize()`, `drawText()` and `drawColoredText()`).
A lot of functions in another classes that uses `Font.measureText()` have buffers like that: see  
`private int[] _lineWidthBuf` or `protected int[] _measuredTextWidths` on editors.d.

**Comment by denizzzka** [comment]
> Font.measureText() not uses this buffer

Uses as `widths` argument:
https://github.com/buggins/dlangui/blob/master/src/dlangui/platforms/console/consolefont.d#L75
https://github.com/buggins/dlangui/blob/master/src/dlangui/graphics/fonts.d#L207

**Comment by and3md** [comment]
> So, after monospaced line 'abc def' is measured _textSizeBuffer will contain something like:
[10, 10, 10, 10, 10, 10, 10] where 10 is width of each letter?
If there all letters have the same width for example 10 that will be
[10, 20, 30, 40, 50] so last letter have all string width.

Thats why there are code like this if you want all string width:
`int charsMeasured = font.measureText(_measuredText, _measuredTextWidths, MAX_WIDTH_UNSPECIFIED, tabSize);`
`stringWidth = charsMeasured > 0 ? _measuredTextWidths[charsMeasured - 1]: 0;`

**Comment by denizzzka** [comment]
Thanks for explanation! I am fixed my version of `measureText` and currently text output works ok!

May be it is reasonable to copy'n'paste this explanation into source code comment on this array?

**Comment by and3md** [comment]
Happy to help. If there are questions, that means docs should be extended.

**Comment by denizzzka** [comment]
One small question: why used `_textSizeBuffer.length = text.length + 1` ? What purpose of +1 width item here?

**Comment by and3md** [comment]
I think there is no meaning. Maybe that's something outdated. Another functions use just length.

**Comment by denizzzka** [comment]
> May be it is reasonable to copy'n'paste this explanation into source code comment about this array?

I am will add some comments in my PR about #386 in short time
