### ISSUE TITLE
WindowFlag.Fullscreen doesn't work in Windows.

### ISSUE THREAD

**Issue by sezak** [buggins/dlangui#393]
window = Platform.instance.createWindow("HelloWorld", null, WindowFlag.Fullscreen | WindowFlag.Resizable);

doesn't create full screen window, but the same as 
window = Platform.instance.createWindow("HelloWorld", null);

**Comment by buggins** [comment]
We can use solution from SDL2 WIN_SetWindowFullscreen

**Comment by buggins** [comment]
Working on it...

**Comment by buggins** [comment]
creation of fullscreen window under win32 is submitted.
TBD: allow to switch app to fullscreen and back.

**Comment by buggins** [comment]
Assuming as fixed.
If it's needed to implement switching to fullscreen and back after window creation, let's submit additional issue.
