### ISSUE TITLE
Application is detected as malware by anti virus software

### ISSUE THREAD

**Issue by andre2007** [buggins/dlangui#395]
On windows 10 (creator update) I run the free anti virus software "Free Antivirus" from Avira.
I created a hello world application and while running "dub" the executable was detected as malware:

Pattern 'TR/ATRAPS.Gen [trojan]'
in file 'C:\Users\user\Desktop\hexviewer\.dub\build\application-debug-windows-x86-dmd_2075-BFF9C11610497CA4CEFF6E1FE9DE9851\hexviewer.exe found.
File was moved to Quarantäne 

{
	"name": "hexviewer",
	"authors": [
		"user"
	],
	"dependencies": {
		"dlangui": "~>0.9.83"
	},
	"description": "A minimal D application.",
	"copyright": "Copyright © 2017, user",
	"license": "proprietary"
}

import dlangui;

mixin APP_ENTRY_POINT;

extern (C) int UIAppMain(string[] args) {

    Window window = Platform.instance.createWindow("DlangUI example - HelloWorld", null);
    window.mainWidget = (new Button()).text("Hello, world!"d).margins(Rect(20,20,20,20));
    window.show();
    return Platform.instance.enterMessageLoop();
}

**Comment by denizzzka** [comment]
What is hexviewer.dub?

**Comment by buggins** [comment]
if you modify something in app, is it detected as malware?
What about building dlangui examples? E.g. dlangui:example1, dlangui:helloworld?

**Comment by andre2007** [comment]
I want to build a hex viewer application therefore I set the name to hexviewer in dub.json. By renaming it to s.th. else the issue with the anti virus application disappears. 
Actually the issue was caused by naming my application "hexviewer"

**Comment by buggins** [comment]
very strange. Does simple renaming of executable after build help?

**Comment by denizzzka** [comment]
Very paranoid antivirus.

**Comment by andre2007** [comment]
While running dub and the creation of the executable, it is immediately moved into quarantine by AntiVirus.

**Comment by buggins** [comment]
Closing as not a dlangui issue.
