### ISSUE TITLE
How to use Dlangui in a fully offline computer

### ISSUE THREAD

**Issue by ASHIT-AXAR** [buggins/dlangui#400]
hello
there is a computer which is unable to connect to internet.
i want to use dlangui to build simple apps there. so i need a way to setup tools on that offline computer to work with. i can download tools (e.g zip files ...) somewhere else and bering those to the offline computer.
i have downloaded and installed DMD and DUB. and also dlangui as ZIP file.
what else is needed to download and how to setup them ?
the only thing matters is that it should work fully offline.

**Comment by buggins** [comment]
there should be some DUB commands to register local repository, but I'm not sure how to use it

**Comment by buggins** [comment]
W/O dub, you can build projects using some IDE like VisualStudio+VisualD, or Mono-D.
Add dlangui library project into your workspace as a dependency.

**Comment by buggins** [comment]
Additional comment from forum http://forum.dlang.org/post/uuvapincxycojqxadoam@forum.dlang.org

Don't worry, DlangUI is stand-alone: you only need the connection to download it, but not to use it nor to compile with. Dub will function without connection if you have already downloaded the needed dependencies.

If you have no connection at all for the device you develop with, you can use dub add-local to register a package you have fetched manually.

**Comment by buggins** [comment]
closing as answered
