### ISSUE TITLE
Argement for `UIAppMain` does not contain its program name

### ISSUE THREAD

**Issue by tom-tan** [buggins/dlangui#403]
In dlangui 0.9.87, the argument of `UIAppMain` only contains its program arguments on Linux systems
but it is inconsistent with `main` in dlang whose first element is its program name.

IMO, this behavior gets us confused.
Also, some functions such as `std.getopt.getopt` need workarounds for it.

Is it a bug or an intended behavior?

**Comment by buggins** [comment]
There was a difference between win and linux parameter list. I modified it to be like in Windows (w/o) exe name.
If another behavior has some advantages (like getopt), I can change it to include executable on all platforms.

**Comment by tom-tan** [comment]
The second reason is about platform independence.

If `UIAppMain` does not provide the argument that contains its program name, 
we have to get it by using platform-dependent way such as `GetModuleFileName` (Win32 API) or `getprogname` (defined in stdlib.h in FreeBSD) or so on.

Although it can be solved If dlangui provides a new function to get the program name,
it is much straightforward to include the program name in the argument of `UIAppMain`.

**Comment by buggins** [comment]
There is a function to get current executable name. But ok, I'll rework code to put it to first arg.

**Comment by buggins** [comment]
reworked arg list format. 
Now its first item contains executable file name on all platforms

**Comment by tom-tan** [comment]
Thanks!
