### ISSUE TITLE
Size/performance issues on win32

### ISSUE THREAD

**Issue by Superbelko** [buggins/dlangui#404]
After commit baec5e04b435e9a90638a729d446dc31ed00b80b there is an issue with widget size measurement that leads to unexpected width calculation, widget takes "infinite" amount of space, such behavior results in severe performance drop. This can be observed in dmledit example.

I've tracked this issue up to the commit above, see also platforms/windows/winapp.d:434  _mainWidget.measure(SIZE_UNSPECIFIED, SIZE_UNSPECIFIED); // <- wrong size measured here

**Comment by buggins** [comment]
@and3md, could you please investigate this?

**Comment by and3md** [comment]
OK, I'll look into it.

**Comment by and3md** [comment]
Before this commit when `layoutWidth`/`layoutHeight` was set to `FILL_PARENT` widgets size was set to max and next proportionally shrinked to window size. That makes problem to measure window size so after commit baec5e0 there is new measure algorithm. 

When measure has parameters `SIZE_UNSPECIFIED, SIZE_UNSPECIFIED` dlangui expect minimal widget size and next size is extended when you have FILL_PARENT flags. 

Percent size code was not changed and that's makes problem.

Quick fix for you is change line 309 of dmledit.d:
`previewLayout.layoutWidth = makePercentSize(50);` to
`previewLayout.layoutWidth = FILL_PARENT`
and add line :
`_editor.minWidth = 350;`

**Comment by Superbelko** [comment]
Ok, thanks for the tip, it works.

**Comment by and3md** [comment]
Percent size code in `measuredContent()` make infinite loop. Widget size change make parent size change and that change widget size etc. Now percent size code is in layout code (`LayoutItems`) and is limited to one widget with percent size. That should be sufficient for most cases. Using percent sizes should be not recommended.
