### ISSUE TITLE
Mouse wheel handled incorrectly

### ISSUE THREAD

**Issue by XuTpuK** [buggins/dlangui#408]
I found this bug in DLangIDE, but seems roots are here. In a tree widget when I use mouse wheel, tree scrolls down despite direction of wheel! Funny and unprofessional.

**Comment by buggins** [comment]
Cannot reproduce. Tried on Windows - both Win32 and SDL backends.

**Comment by XuTpuK** [comment]
What's funny, NOW I cannot reproduce too! (I tried to make a video) Well, false alarm, sorry!
Hope it's not "floating bug".

**Comment by denizzzka** [comment]
Sometimes my mouse works as described here in any application. I think this is hardware bug.

**Comment by XuTpuK** [comment]
@denizzzka : I wish it was mouse bug, but I never had such problem with my mouse (it's MS brand). "One way" scroll happen only in DLangIDE and only once - now it works fine. Magic...

**Comment by buggins** [comment]
:)
