### ISSUE TITLE
X11: Popup menu issues

### ISSUE THREAD

**Issue by FenixFyreX** [buggins/dlangui#413]
I've been testing dlangui and figuring out how to use the library as a whole, and I've found a few issues with using the `x11` backend in regards to right click events and/or popup menu(s).

Building example1 with the following command (build can be release or debug, doesn't matter):
`dub run dlangui:example1 --config=x11`
When I move into the editor tab and right click the first editor, nothing happens. Instead, when I middle click, the context menu pops up. Interestingly, I can create two context menus at the same time this way.

This does not happen when using the de-facto SDL2 backend (right click functions normally / only one context menu pops up).

Running on ArchLinux 64 bit (x86_64) with openbox window manager.

**Comment by FreeSlave** [comment]
I would not consider x11 backend as ready to use. It needs development.

**Comment by and3md** [comment]
@FenixFyreX  I think it's fixed now by fd6940c18413ac5747a457b4f67febd42210cc67 and 4c6cc85481ddbe1f6d8ebb873af5728ceddb3ee9. Please test and close when version 0.9.162 will be released. 
@buggins Please test latest X11 changes and make release :)

**Comment by FenixFyreX** [comment]
Solved, thanks much :)
