### ISSUE TITLE
Alt+key does not work

### ISSUE THREAD

**Issue by dukc** [buggins/dlangui#414]
I'm using windows32 default build. I can't type '{', or any other alt-character neither by pressing control-leftAlt, nor with right alt (it has text "alt Gr" on my keyboard). Shift and Control work as they should.

I encountered this in DLangIDE but I tested the same thing in my own project which uses EditBox and it applied there too.

**Comment by buggins** [comment]
It's bug in support of Alt+a..z shortcuts - protection from generation of character.

**Comment by buggins** [comment]
What is your keyboard layout? I'm trying to reproduce...

**Comment by dukc** [comment]
It's Finnish.

**Comment by dukc** [comment]
If Visual Studio is used as model, it won't allow characters with left alt either. Only "Alt Gr" works.

**Comment by buggins** [comment]
Probably fixed in v0.9.106
Could you please confirm?

**Comment by dukc** [comment]
I'll do that when I get home. You were quick as always... just don't exhaust yourself 👍 .

**Comment by buggins** [comment]
Submitted additional fix for SDL backend.
Tested on Win32 only.
v0.9.107

**Comment by dukc** [comment]
With DLangIDE 0.7.64 "default" and DLangUI 0.9.111 "default" works now like dream. Thank you.
