### ISSUE TITLE
DMD 2.075.1/076 "Out of memory" build crash starting release 0.9.93 on Win 7 x32 [RU]

### ISSUE THREAD

**Issue by kildin** [buggins/dlangui#425]
Начиная с релиза UI 0.9.93 невозможно собрать ни примеры из папки "Examples", ни использующий Dlang UI проект DLang IDE. 
Тестируемая машина: I3-550, 4Gb Озу, Windows 7 Sp1 Pro X32 русская со всеми установленными обновлениями. Специально для тестирования была создана новая учетная запись Windows, чтобы исключить любые побочные эффекты. 

На первом скриншоте попытка собрать последнюю версию Dlang IDE
![out_of_memory](https://user-images.githubusercontent.com/31731315/30192248-1198a354-944f-11e7-9457-835d17537fe8.jpg)
Далее последовательно скачивались релизы Dlang UI и собирался example1 с целью определения версии, с которой началась данная проблема
![out_of_memory2](https://user-images.githubusercontent.com/31731315/30192268-32ee8320-944f-11e7-8ae8-818efa481140.jpg)
Как видно по скриншоту, на 0.9.92 example1 еще успешно собирается, начиная с 0.9.93 попытка сборки оканчивается вылетом DMD с "Out of memory"

**Comment by buggins** [comment]
This issue is probably caused by commit 1673b3103ed41ede8de5396e44d6bffa654ade08

**Comment by buggins** [comment]
I don't have 32bit windows.
Could you please try to build example1 on v0.9.118?
If not fixed, try to comment out `metadata.d` line 5: 

    version = GENERATE_PROPERTY_METADATA;

**Comment by kildin** [comment]
Получилось, но только после комментирования указанной строки в metadata

**Comment by kildin** [comment]
Тут нужно еще наверное упомянуть, что в конфигурациях minimal и console компиляция проходит

**Comment by Superbelko** [comment]
Seems like DMD is built with "large adress aware" support, so on 64 bit system it takes slightly more than 2gb of memory and compiles successfully.

IIRC DMD turns off GC for compiling speed up, so memory usage rises until it runs out of memory.
I'll try to look into this issue and try to reduce amount of garbage created in the process.

**Comment by buggins** [comment]
probably fixed. Could someone confirm?

**Comment by kildin** [comment]
Одна UI собирается. Но при попытке собрать IDE все тот же out of memory

**Comment by buggins** [comment]
IDE использовала предыдущую версию dlangui. Попробуй обновиться до v0.8.8

**Comment by kildin** [comment]
2.075.1 - полет нормальный. Вечером обновлюсь на 076.1 и проверю с ним
