### ISSUE TITLE
Building with LDC fails on Windows due to win_app.def

### ISSUE THREAD

**Issue by Superbelko** [buggins/dlangui#436]
Building with LDC is currently ends up with following error:

/DEF:..\..\src\win_app.def: no such file or directory
Error: llvm-lib.exe failed with status: 1
ldc2 failed with exit code 1.

Can we change dub.json line (34) with sourceFiles-windows to something more reasonable?
like

 "sourceFiles-windows-x86-dmd": ["$PACKAGE_DIR/src/win_app.def"],

I haven't tested it with GDC and don't use it, but I don't think it ever uses this .def files. As I aware of, only optlink uses them so x86 specialization seems to be best option IMHO.

**Comment by buggins** [comment]
try v0.9.129

**Comment by Superbelko** [comment]
It works now. Tested with dmd x86, x86 mscoff, x64, and ldc x86 & x64. Thank you!

But please consider changing this to sourceFiles-windows-x86-dmd, because every target except dmd x86 gives linker warning about unsupported operators EXETYPE and SUBSYSTEM. 
The same is true for user's code that also uses win_app.def. The MS linker uses Windows subsystem by default when WinMain is present[1], so this is really only relevant to dmd x86 and optlink.

p.s. probably readme.md section about win_app.def should be updated too to be clear on that it is about win32 x86 only.

[1] https://msdn.microsoft.com/ru-ru/library/windows/desktop/fcc1zstk(v=vs.120).aspx

**Comment by buggins** [comment]
done
