### ISSUE TITLE
Language Highlighting in Readme

### ISSUE THREAD

**Issue by MggMuggins** [buggins/dlangui#443]
Github Markdown lets you do language highlighting in your readmes and on the wiki. If the wiki is open to edit, I'll go add that support now, but seeing the readme with good highlighting would be good too, both D and sh.
Put the name of the language after the first set of triple backtics.

**Comment by MggMuggins** [comment]
I just finished formatting all the wiki pages.

**Comment by buggins** [comment]
Thank you! I didn't know it.

**Comment by MggMuggins** [comment]
CODING_STYLE.md could use this as well. I'm pretty sure that the wiki is all good.
