### ISSUE TITLE
Compile Error when using Widget.childByID

### ISSUE THREAD

**Issue by MggMuggins** [buggins/dlangui#444]
On the Getting Started page, it has this:
## Accessing child widgets

Often, especially when layout is created by loading from DML, you need access to child items.

Use `childById` method to search in widget tree by widget id.

You have to specify widget ids to use childById method.

Example:

```d
// create layout from DML
auto layout = parseML(q{
    TableLayout {
        colCount: 2
        margins: 20; padding: 10
        backgroundColor: "#FFFFE0"
        TextWidget { text: "Label 1" }
        EditLine { id: edParam1; text: "Some text for parameter 1" }
        TextWidget { text: "Label 2" }
        EditLine { id: edParam2; text: "Some text for parameter 2" }
        TextWidget { text: "Label 3" }
        ComboBox { id: cbOptions }
        TextWidget { text: "Some buttons" }
        HorizontalLayout {
            Button { id: btnOk; text: "Ok" }
            Button { id: btnCancel; text: "Cancel" }
        }
    }
});
// access individual widgets by id
layout.childById("btnOk").click = delegate(Widget src) {
    showMessageBox("Editors content:"d, "Edit1: "d ~ layout.childById("edParam1").text);
};
```
This Code does not compile. showMessageBox() is a method of Window.

This code doesn't compile either, but for a different reason. This is in the same file in the same dub project, just comments in different places:
```D
Widget layout = parseML(q{
    TableLayout {
        colCount: 2
        margins: 20; padding: 10
        backgroundColor: "#FFFFE0"
        TextWidget {
            text: "Label 1"
        }
        EditLine {
            text: "Some text for parameter 1"
        }
        TextWidget {
            text: "Label 2" 
        }
        EditLine {
            text: "Some text for parameter 2"
        }
        TextWidget {
            text: "Label 3" 
        }
        ComboBox {
            items: ["String1", "String2", "String3"]
        }
        TextWidget {
            text: "Some buttons"
        }
        HorizontalLayout {
            Button {
                id: "btnOk"
                text: "Ok"
            }
            Button {
                id: "btnCancel"
                text: "Cancel"
            }
        }
    }
});
    
layout.childByID("btnOk").click = delegate(Widget src) {
    window.showMessageBox("Saved!");
    //return true;
};
layout.childByID("btnCancel").click = delegate(Widget src) {
    window.close();
    //return true;
};
```
This gives the error: `Error: no property 'childByID' for type 'dlangui.widgets.widget.Widget', did you mean 'childById(T = typeof(this))(string id, bool deepSearch = true)'?`

Doesn't matter what import solution I use, whether I try to specify imports or not. Nothing will do.

I suspect that all those public imports in all the modules has something to do with this. In general the import situation is difficult to understand at best. There are so many modules that publically import a lot of other modules that it's hard to understand how it all fits together. A rework of that organization would be good.

**Comment by buggins** [comment]
It should be `childById`, not `childByID`

**Comment by MggMuggins** [comment]
Thanks, I got it working! I'll edit Getting Started...
