### ISSUE TITLE
Everything appears very large (Linux/X11)

### ISSUE THREAD

**Issue by whiteisthenewblack** [buggins/dlangui#463]
Hi,

When I start any DlangUI project, all the controls are particularly large on my system. Other GUI programs work fine.

![screenshot](https://i.imgur.com/uHTfxD8.png)

I'm assuming this isn't supposed to happen. Does anyone know what might cause it?

**Comment by buggins** [comment]
High DPI screen is detected.
Not sure what to do with it.

**Comment by whiteisthenewblack** [comment]
The screen is 140dpi.

How does DlangUI detect this? Maybe I can change that

**Comment by buggins** [comment]
Dlangui reads screen DPI using SDL2 calls.
Default DPI is 96. So, for 140 everything will be scaled.

**Comment by buggins** [comment]
possible workaround - allow application to override system DPI.
E.g. calling overrideSystemDPI(96) would disable scaling.
overrideSystemDPI(0) would reenable usage of detected DPI.
As well it will be possible to choose custom UI scaling by application - e.g. somewhere in settings.

**Comment by FreeSlave** [comment]
If you really want to stick to X11 dlangui version (which I would not recommend, since this platform implementation is currently incomplete in dlangui, e.g. getting clipboard contents does not work) you may try to use XRandr calls. See https://lists.x.org/archives/xorg-devel/2017-April/053430.html

**Comment by whiteisthenewblack** [comment]
What alternative do I have if I want to use Dlangui on Linux?

**Comment by FreeSlave** [comment]
SDL2. This is default configuration.

**Comment by whiteisthenewblack** [comment]
My apologies. I meant X11 as in the underlying gfx server, as opposed to Wayland. I'm using the SDL back end for Dlangui. I wasnt aware there was an X11 one.

**Comment by FreeSlave** [comment]
Check if SDL2 version is at least 2.0.4. That's when SDL_GetDisplayDPI was added. You'll get message "SDL_GetDisplayDPI is not found: cannot detect screen DPI" if this function is missed.

**Comment by buggins** [comment]
Implemented overriding of detected screen DPI.
To disable scaling, add to your app UIAppMain() 

     overrideScreenDPI(96);

**Comment by whiteisthenewblack** [comment]
Perfect, thank you! I'll test this later today.
