### ISSUE TITLE
Setting window size does not work

### ISSUE THREAD

**Issue by whiteisthenewblack** [buggins/dlangui#466]
Hello again,

When I run the [createWindow](https://buggins.github.io/dlangui/ddox/dlangui/platforms/common/platform/Platform.createWindow.html) function specifying a width and height for the window, this has no effect.

Example code:

```d
import dlangui;

mixin APP_ENTRY_POINT;

extern (C) int UIAppMain(string[] args) {
	Window window = Platform.instance.createWindow("Test", null, WindowFlag.Resizable, 800, 800);
	window.mainWidget = (new TextWidget).text("This window should be 800x800, but it isn't");
	window.show;
	return Platform.instance.enterMessageLoop();
}
```

This issue also seems to be present in the `ircclient` example. Here it is at its default size:

![ircclient screenshot](https://i.imgur.com/J6JPNlk.png)

Am I missing something here?

**Edit**: appears to be a recent issue. Works as expected with Dlangui 0.9.149, but not with 0.9.157

**Comment by and3md** [comment]
I think that can be because default resize mode was set to WindowOrContentResizeMode.resizeWindow try change it to WindowOrContentResizeMode.scrollWindow. I will test it tomorrow.

**Comment by whiteisthenewblack** [comment]
@and3md Yeah, that solves it. What was the reason for this change in the first place?

**Comment by and3md** [comment]
I think that is a bug in resizeWindow flag. It should only make window bigger if content is bigger than size in construction.

**Comment by and3md** [comment]
Fixed by 5584362bd8d047b13104b112e91dafc55e961047.
@buggins maybe better set default to `WindowOrContentResizeMode.scrollWindow` and when you want resized window at start add `WindowFlag.MeasureSize`? But that will make window smaller in some cases.

**Comment by and3md** [comment]
@whiteisthenewblack Please test v 0.9.162 and close if works for you. Now default is `WindowOrContentResizeMode.scrollWindow` and scrollbar appear if main widget need more space. If you want you can expand window to min widget with flag `WindowFlag.ExpandSize` (then if user change window size to smaller scrollbars appear).

**Comment by and3md** [comment]
I think it can be closed. Reopen if you have any problems with that.
