### ISSUE TITLE
[x11] State.Hovered is not set on other buttons after clicking on some button

### ISSUE THREAD

**Issue by FreeSlave** [buggins/dlangui#474]
That's actually long-standing bug I kept forgetting to report.
If in X11 you click some button then other buttons stop to set `State.Hovered` on mouse motion events until you click some button again.
Another (probably related) bug is that the text (but not the background) on the button stays hovered even if mouse if out of button geometry.
I could not get to the root of the problem. Could you look at this?

**Comment by and3md** [comment]
@FreeSlave Oh, commit with fix description closed this automatically. Please test and reopen if not working.

**Comment by FreeSlave** [comment]
Looks good. Thanks
