### ISSUE TITLE
[wish] Add support of EditorConfig config files

### ISSUE THREAD

**Issue by denizzzka** [buggins/dlangui#503]
http://editorconfig.org/

What is EditorConfig?

EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems.

File Format Details
EditorConfig files use an INI format that is compatible with the format used by Python ConfigParser Library, but [ and ] are allowed in the section names. The section names are filepath globs, similar to the format accepted by gitignore. Only forward slashes (/, not backslashes) are used as path separators and octothorpes (#) or semicolons (;) are used for comments. Comments should go on their own lines. EditorConfig files should be UTF-8 encoded, with either CRLF or LF line separators.

**Comment by FreeSlave** [comment]
Do you mean to add .editorconfig to dlangui repository to define dlangui code style or add support for EditorConfig in EditBox widget?

**Comment by kildin** [comment]
Имелось ввиду (изначально в группе ВК) поддержка вцелом формата в IDE, и наверное правильно этот  запрос было бы разместить в https://github.com/buggins/dlangide/issues

**Comment by denizzzka** [comment]
> or add support for EditorConfig in EditBox widget?

This

**Comment by denizzzka** [comment]
> и наверное правильно этот запрос было бы разместить в https://github.com/buggins/dlangide/issues

Ой, я не туда написал, прошу прощения.
