### ISSUE TITLE
dlangui.widgets.widget.Widget.text isn't implemented

### ISSUE THREAD

**Issue by FreeSlave** [buggins/dlangui#510]
```
core.exception.AssertError@src/dlangui/widgets/widget.d(574): dlangui.widgets.widget.Widget.text isn't implemented
```
Got this error when running example1 on master.
@denizzzka when make prs please make sure that at least example1 is working.

Note: faulty component is VerticalLayout

**Comment by denizzzka** [comment]
I'll fix it.

[ru]
Специально безусловный ассерт поставил - думал вылезет на этапе CI. Сорри!

Но вопрос глубже: что такое Widget.text? Виджетов, которые показывают текст не так уж и много. Какой может быть текст у VerticalLayout?

Сейчас я сделаю быстрофикс (уберу assert), но надо бы порешать нужен ли всем виджетам метод text. (Моё предложение: в интерфейс это вытащить.)

**Comment by denizzzka** [comment]
Fixed in https://github.com/buggins/dlangui/pull/512
