### ISSUE TITLE
LogWidget Style

### ISSUE THREAD

**Issue by triplejam** [buggins/dlangui#511]
There isn't a way to change the font of a LogWidget through a theme. There isn't a styleid of its own and I don't think adding one works. In the constructor

> this(string ID) {
        super(ID);
        _scrollLock = true;
        _enableScrollAfterText = false;
        enabled = false;
        fontSize = makePointSize(9);
        //fontFace = "Consolas,Lucida Console,Courier New";
        fontFace = "Menlo,Consolas,DejaVuSansMono,DejaVu Sans Mono,Lucida Sans Typewriter,Courier New,Lucida Console";
        fontFamily = FontFamily.MonoSpace;
        minFontSize(pointsToPixels(6)).maxFontSize(pointsToPixels(32)); // allow font zoom with Ctrl + MouseWheel
        onThemeChanged();
    }

default fonts are set manually. But if commented out the LogWidget will use EDIT_BOX style.

**Comment by and3md** [comment]
@triplejam Do you want change style at runtime? There is example how to do that in https://github.com/buggins/dlangui/issues/502

**Comment by triplejam** [comment]
No, I understand changing it at runtime, changing the font in the dml works as well. I am just asking if the line: 

> fontFace = "Menlo,Consolas,DejaVuSansMono,DejaVu Sans Mono,Lucida Sans Typewriter,Courier New,Lucida Console";

Could be removed without causing any issues. Since that way the EDIT_BOX style could take precedence for the font.

**Comment by and3md** [comment]
@triplejam Now I understand your issue. You are right. When widget need change default visual view should have it's own style. There will be `LOG_WIDGET` when #516 will be accepted and merged.

**Comment by triplejam** [comment]
Ok, nice
