### ISSUE TITLE
ImageTextButton: textColor and fontSize methods is ignored

### ISSUE THREAD

**Issue by denizzzka** [buggins/dlangui#519]
Code like:
```D
hl1.childById("BUTTON_SUBMIT_0").textColor("green").fontSize(16).fontWeight(800).fontFace("Courier");
```
isn't affects anything.

For `Button` this code works ok.

**Comment by buggins** [comment]
It's because internally ImageButton consists of parent widget and children.
You change parent widget's style

**Comment by denizzzka** [comment]
So, it should be resolved as bug or feature. (It is important for my new html backend affected by this issue too)

**Comment by denizzzka** [comment]
[RU] Похоже на отголосок вот той ситуации, что я недавно откатил этим ПР https://github.com/buggins/dlangui/pull/512

Всё-таки было бы здорово заменить все "корневые" методы Widget такими же заглушками-ассертами. Даже ценой поломавшихся примеров и некоторых программ, которые используют редкоиспользуемые виджеты, которые этим действием будут поломаны - лучше так, чем иметь подобные скрытые ошибки.

**Comment by and3md** [comment]
@denizzzka This bug was a bigger one. Not only ImageTextButton but also UrlImageTextButton, RadioButton, CheckBox, LinkButton was affected.
