### ISSUE TITLE
enableCloseButton == true in TabItemWidget actually hides the close button

### ISSUE THREAD

**Issue by theyamo** [buggins/dlangui#52]
So I think it should act in reverse?
tabs.d, ~line 112:
        if (_enableCloseButton) {
            _closeButton.visibility = Visibility.Gone;
        } else {
            _closeButton.visibility = Visibility.Visible;
        }

add ! to the if statement and it should act how it probably was intented.

**Comment by buggins** [comment]
Fixed.
