### ISSUE TITLE
Font rendering issue

### ISSUE THREAD

**Issue by pontusm** [buggins/dlangui#526]
There seems to be a problem with the font rendering in DLangIDE. I'm running with the standard settings (have not changed anything after build with Visual Studio) and I'm getting some strange spacing issues between certain letters (see screenshot). It looks like proper kerning information is not taken into consideration when laying out the glyphs. It is noticable between certain character pairs such as OM, OL, AL, RD etc etc.

However, when I run the HelloWorld example in DLangUI the fonts look ok there, so I'm not sure that it is a bug. Maybe you have an idea about what could cause this?

![image](https://user-images.githubusercontent.com/144051/33514712-2c357762-d759-11e7-8163-4ee2cd269396.png)

**Comment by pontusm** [comment]
I just found out that if I run DLangIDE using dub it works better and the fonts look ok. Not great, but at least better.

I'm guessing that there must be some setting that is different when building and running with Visual Studio?

![image](https://user-images.githubusercontent.com/144051/33516145-dea43776-d76d-11e7-9611-1f601ef98550.png)

**Comment by buggins** [comment]
The difference is in freetype usage. If freetype is found, it's being used instead of win32 rendering.
DUB copies libfreetype dll to bin directory.
Just do the same for VS project - put DLL from dlangui/libs/... to Debug and Release subdirs in project.

**Comment by pontusm** [comment]
Excellent, that solved my problem. Thanks!
