### ISSUE TITLE
DMLedit bugs

### ISSUE THREAD

**Issue by nicesai** [buggins/dlangui#530]
In DMLedit example program, there are couple of bugs at line 261:

This is original:
            case IDEActions.FileSave:
                if (_content.modified)
                    a.state = ACTION_STATE_ENABLED;
                else
                    a.state = ACTION_STATE_DISABLED;
                return true;

Should be changed to:
           case IDEActions.FileSave:
                if (_editor.content.modified)
                    a.state = ACTION_STATE_ENABLED;
                else
                    a.state = ACTION_STATE_DISABLE;
                return true;

**Comment by triplejam** [comment]
just fixed see #525 and #528 I think it should be correct now in v0.9.173

**Comment by buggins** [comment]
can I close it? is it fixed in recent label?

**Comment by triplejam** [comment]
@buggins It's not fixed in label v0.9.173

**Comment by GrimMaple** [comment]
Appears to be fixed as of now
