### ISSUE TITLE
SplitPane?

### ISSUE THREAD

**Issue by nicesai** [buggins/dlangui#531]
Does DLangUI has SplitPane? Like JSplitPane in java swing? 
I was using DMLEdit.d and I couldn;t resize the panels. If the lib has split-pane like widgets, it would help dmledit, and also I would like to use them a lot.

**Comment by nicesai** [comment]
I noticed that dlangIDE already used JSplitPane like layout. Can that be added to the DlangUi library?

**Comment by triplejam** [comment]
It is already. I think it's just not obvious how to use it. There's a ResizerWidget that resizes the two widgets on the sides of it. But the easier thing to do is to use DockHost and DockWindow's which will make the resizers. For example 

    DockHost noteHost = new DockHost();
    DockWindow noteTreeWindow = new DockWindow("noteTreeWindow");
    noteTreeWindow.bodyWidget(notebookTree);
    noteTreeWindow.dockAlignment(DockAlignment.Left);
    noteHost.addDockedWindow(noteTreeWindow);
    noteHost.bodyWidget(noteLayout);

It would be useful to be able to do this in dml

**Comment by buggins** [comment]
ResizerWidget is not implemented well.

**Comment by nicesai** [comment]
I added ResizerWidget between other panels and in the GUI I can see a thick line where the resizer is present. But I couldn't drag it, and it does not resize other panels. How to make it work? Is there an example how to use the ResizerWidget?

Buggins said ResizerWidget is not implemented well, does that mean its a bug?

**Comment by buggins** [comment]
Going to implement proper ResizerWidget behavior under this issue.

**Comment by nicesai** [comment]
I am using DockHost as a containment as for now as suggested by triplejam (thanks btw), seems to work ok. But when I nest it, the splitter-bar for the inner dockhost is not responsive when dragged with mouse, its jerky and is not refreshing when dragging. 

Is the DockHost nestable? And is there any way to prevent the jerky motion as mentioned above?

**Comment by nicesai** [comment]
I modified the createBody function as below:

    override protected Widget createBody() {
        
        Widget leftPanel2;
        {
            WidgetsList widgetsList = new WidgetsList();
            StringListWidget propList = new StringListWidget();
            auto sla = new StringListAdapter();
            foreach(const ref widget; getRegisteredWidgetsList())
            {
                auto propertyListAdapter = new StringListAdapter();
                if ( auto meta = findWidgetMetadata(widget) )
                {
                    foreach(prop; meta.properties)
                    {
                        propertyListAdapter.add(UIString.fromRaw(prop.name ~ "   [" ~ to!string(prop.type) ~ "]" ));
                        propListsAdapters[widget] = propertyListAdapter;
                    }
                }
                sla.add(UIString.fromRaw(widget));
            }
        
            widgetsList.adapter = sla;

            widgetsList.itemClick = delegate (Widget source, int itemIndex){
                propList.adapter = propListsAdapters[to!string(widgetsList.selectedItem)];
                return true;
            };
            widgetsList.onItemDoubleClick = delegate (Widget source, int itemIndex) {
                auto caret = _editor.caretPos;
                auto widgetClassName = widgetsList.selectedItem;
                EditOperation op = new EditOperation(EditAction.Replace, caret, widgetClassName);
                _editor.content.performOperation(op, this);
            };

            leftPanel2 = addSplitter(widgetsList, propList, null, null, null);
        }

        {
            _editor = new DMLSourceEdit();
            _editor.text = SAMPLE_SOURCE_CODE;
        }
        
        VerticalLayout previewLayout = new VerticalLayout();
        {
            auto previewControls = new HorizontalLayout();                        
            {
                auto cbFillHorizontal = new CheckBox(null, "Fill Horizontal"d);
                auto cbFillVertical = new CheckBox(null, "Fill Vertical"d);
                auto cbHighlightBackground = new CheckBox(null, "Background"d);
                cbFillHorizontal.checkChange = delegate(Widget source, bool checked) {
                    _fillHorizontal = checked;
                    updatePreview();
                    return true;
                };
                cbFillVertical.checkChange = delegate(Widget source, bool checked) {
                    _fillVertical = checked;
                    updatePreview();
                    return true;
                };
                cbHighlightBackground.checkChange = delegate(Widget source, bool checked) {
                    _highlightBackground = checked;
                    updatePreview();
                    return true;
                };
                
                previewControls.addChild(cbFillHorizontal);
                previewControls.addChild(cbFillVertical);
                previewControls.addChild(cbHighlightBackground);
            }

            {
                _preview = new ScrollWidget();
                _preview.layoutWidth = FILL_PARENT;
                _preview.layoutHeight = FILL_PARENT;
                _preview.backgroundImageId = "tx_fabric.tiled";
            }
            
            previewLayout.layoutWidth = makePercentSize(50);
            previewLayout.layoutHeight = FILL_PARENT;
            previewLayout.addChild(previewControls);
            previewLayout.addChild(_preview);
        }
        
        {
            Widget hlayout2 = addSplitter(_editor, null, previewLayout, null, leftPanel2);
            VerticalLayout bodyWidget = new VerticalLayout();
            bodyWidget.layoutWidth = FILL_PARENT;
            bodyWidget.layoutHeight = FILL_PARENT;
            bodyWidget.addChild(hlayout2);
            return bodyWidget;
        }    
    }

    private Widget addSplitter(Widget center, Widget top, Widget right, Widget bottom, Widget left) {
        DockHost host = new DockHost();
        Widget[] widgets = [top, right, bottom, left];
        DockAlignment[] aligns = [DockAlignment.Top, DockAlignment.Right, DockAlignment.Bottom, DockAlignment.Left];
        // should rewrite to use the normal order of enum

        for (int k=0; k<widgets.length; k++) {
            Widget widget = widgets[k];
            if (widget is null) continue;
            
            DockWindow win = new DockWindow("Win");
            win.bodyWidget(widget);
            win.dockAlignment(aligns[k]);
            host.addDockedWindow(win);
        }
               
        host.bodyWidget(center);
        return host;
    }

**Comment by nicesai** [comment]
Maybe I should open a separate issue for this? As the original one is meant for the Resizer widget?

**Comment by GrimMaple** [comment]
Implemented resizers

**Comment by nicesai** [comment]
Thank you GrimMaple. Will try testing it.
