### ISSUE TITLE
ListWidget + WidgetListAdapter = child widgets don't work

### ISSUE THREAD

**Issue by drug007** [buggins/dlangui#538]
The following code:
```D
class CustomWidget :  ListWidget {
    this(string ID = null) {
        super(ID);
        styleId = STYLE_EDIT_BOX;

        import dlangui.widgets.lists;
        WidgetListAdapter adapter = new WidgetListAdapter();
        {
            auto tree = new TreeWidget(1.text, ScrollBarMode.Auto);
            tree.parent = this;
            auto child = tree.items.newChild("g1_1", "Group 1");
            foreach(j; 0..3)                
                child.newChild("g1_" ~ j.text, "item "d ~ j.dtext);
            adapter.add(tree);
        }
        ownAdapter = adapter;
        requestLayout();
    }
}
```
creates a widget, where child widget (TreeWidget) does not react to mouse or keyboard input. @buggins Does WidgetListAdapter support menu only? And functionality for general widget list adapter is not provided yet?

**Comment by drug007** [comment]
I found that using `tree.styleId("LIST_ITEM");` makes the situation better - I can select an item, scroll them by means both mouse and keyboard. But child TreeWidget doesn't work still.

**Comment by drug007** [comment]
I found that using `styleId = STYLE_LIST_BOX;` + `tree.styleId = LIST_ITEM;` makes the situation better - I can select and scroll widgets by means both mouse and keyboard, but TreeWidget doesn't work still.

**Comment by triplejam** [comment]
@drug007 I could be wrong but I think ListWidgets are more meant for use with text. You could also try extending VerticalLayout for your custom widget.

**Comment by drug007** [comment]
ListWidgets is base for Menu widget, for text there is StringListWidget (or some widget like this). But you're right in sense it seems I need to make this custom widget...

**Comment by whitebyte** [comment]
Unfortunately my last fix works only partially. While ListWidget children now react to mouse events, their children don't. It means that if there are interactive elements inside a child (such as text inputs, buttons), they are still non-interactive. Their parent (i.e. ListWidget adapter child) steals all the events.
