### ISSUE TITLE
hello im beginer and have trouble on install and star

### ISSUE THREAD

**Issue by KimSH1238** [buggins/dlangui#555]
i saw tutorial of dlangui but i cant install and start.
i dont know how to do and i installed in external ssd so my folder is different than others.

i reeeeallly cant start with text guide. and i dont know what i open and what to do.

if u can take screenshot or simple video, please post up. i have truoble.

but i want to use dlangui and be good at. but impossible for my now skills and knowledge

**Comment by denizzzka** [comment]
DlangUI uses DUB:
http://code.dlang.org/getting_started
