### ISSUE TITLE
the dub.json files isn't match the project structure.

### ISSUE THREAD

**Issue by xfront** [buggins/dlangui#56]
main dub.json changed(so change examples dependency as "dlangui": "*" ): 
{
    "name": "dlangui",
    "description": "Cross platform GUI for D. Layouts, styles, themes, unicode, i18n, OpenGL, widget set.",
    "homepage": "https://github.com/buggins/dlangui",
    "license": "Boost",
    "authors": ["Vadim Lopatin"],
    "buildRequirements":[
        "allowWarnings"
    ],
    
    "targetName": "dlangui",
	"targetPath": "lib",
	"targetType": "staticLibrary",

	"versions-posix": ["USE_SDL", "USE_OPENGL"],
	"versions-windows": ["Unicode", "USE_FREETYPE"],
	"versions": ["EmbedStandardResources"],

	"copyFiles-windows": ["lib/libfreetype-6.dll", "lib/zlib1.dll"],

	"sourcePaths": [
		"3rdparty", "src"
	],

	"importPaths": [
		"3rdparty", "src"
	],

	"stringImportPaths": [
		"views",
		"views/res",
		"views/res/mdpi",
		"views/res/i18n"
	],

	"dependencies": {
		"derelict-gl3": ">=1.0.12",
		"dlib": ">=0.4.1",
		"derelict-ft": ">=1.0.0",
		"derelict-sdl2": ">=1.9.1"
	},
	
    "-ddoxFilterArgs": ["--unittest-examples", "--min-protection=Protected", "--ex", "win32.", "--ex", "src.dlangui"],

    "subPackages": [
        "./examples/helloworld/",
        "./examples/example1/",
        "./examples/tetris/"
    ] 
}

**Comment by buggins** [comment]
Fixed, thanks.
