### ISSUE TITLE
dimage.stream.ArrayStream.readBytes imports std.c.string: compilation error

### ISSUE THREAD

**Issue by Dechcaudron** [buggins/dlangui#570]
Getting this compilation error when trying out the "hello world" in the Wiki, with DMD 2.081:
```d
..\\..\\..\\AppData\\Local\\dub\\packages\\dlangui-0.9.178\\dlangui\\3rdparty\\dimage\\stream.d(226,16): Error: module `string` is in file 'std\c\string.d' which cannot be read
```
The line in question reads `import std.c.string;`. I do not know what it is supposed to reference. I assume `core.stdc.string`. Maybe the former was deprecated in a recent DMD version?

Regards,
Héctor

**Comment by triplejam** [comment]
Yes, I believe you are correct. I noticed this too.

**Comment by buggins** [comment]
Seems like fixed.
(If doesn't build, do upgrade --force-remove)
