### ISSUE TITLE
std.c.string not found

### ISSUE THREAD

**Issue by logicfish** [buggins/dlangui#573]
`...\dub\packages\dlangui-0.9.178\dlangui\3rdparty\dimage\stream.d(226,16): Error: module `string` is in file 'std\c\string.d' which cannot be read`

```
$ dmd --version
DMD32 D Compiler v2.081.2

```
The import needs changing to core.stdc.string.

**Comment by ZombineDev** [comment]
This seems to have been already fixed:
https://github.com/buggins/dlangui/pull/571/files

**Comment by artemirq** [comment]
@logicfish Yeah, it's fixed. We try to build `dlangide`, which have dependency `dlangui`. It means, what latest release `dlangui` with not latest changes

@ZombineDev Issue can be closed. It remains only to understand how to use freshly builded `dlangui` as dependency for `dlangide`

**Comment by logicfish** [comment]
I just edited the file stream.d in place.
