### ISSUE TITLE
Unresolvable dependencies

### ISSUE THREAD

**Issue by MistrzPiwny** [buggins/dlangui#579]
hi,

When i try build any project with dlangui as dependency i got this message:
`Unresolvable dependencies to package derelict-util:
  derelict-ft 1.1.3 depends on derelict-util ~>2.0.6
  derelict-gl3 1.0.24 depends on derelict-util >=1.0.3
`

**Comment by dangbinghoo** [comment]
dub fetch derelict-gl3
dub build derelict-gl3

then, manually modify  	derelict-gl3-1.0.24 's dub 
"dependencies": {
		"derelict-util": "~>2.0.6"
	}

solved this. 
so, this is a problem of package derelict-gl3. not  dlangui.
