### ISSUE TITLE
opengl example won't compile under Linux

### ISSUE THREAD

**Issue by chriscamacho** [buggins/dlangui#581]
I cloned the repo and changed to the examples/opengl directory, after running dub I notice this in the output

src/openglexample.d(36,8): Error: module `gl3` is in file 'derelict/opengl3/gl3.d' which cannot be read

I have made my own experiments with both the old and new derelict version of the opengl (3v3) which work just great

I'm using a 64 bit Linux, happy to try suggestions...

**Comment by triplejam** [comment]
It's not finding the file in the spot it wants so just make a symlink if you need to.

**Comment by cym13** [comment]
Unless I'm missing something it's not that easy, no matter how I try changing the imports to provide it gl3.d and gl.d I get the following bunch of errors:

    opengl ~master: building configuration "application"...
    src/openglexample.d(138,31): Error: undefined identifier glLightfv
    src/openglexample.d(155,18): Error: undefined identifier GL_LIGHTING
    src/openglexample.d(156,18): Error: undefined identifier GL_LIGHT0
    src/openglexample.d(159,19): Error: undefined identifier GL_LIGHTING
    src/openglexample.d(160,19): Error: undefined identifier GL_LIGHT0
    src/openglexample.d(394,5): Error: undefined identifier glShadeModel
    src/openglexample.d(396,5): Error: undefined identifier glNormal3f
    src/openglexample.d(399,5): Error: undefined identifier glBegin
    src/openglexample.d(402,9): Error: undefined identifier glVertex3f
    src/openglexample.d(403,9): Error: undefined identifier glVertex3f
    src/openglexample.d(405,13): Error: undefined identifier glVertex3f
    src/openglexample.d(406,13): Error: undefined identifier glVertex3f
    src/openglexample.d(410,5): Error: undefined identifier glEnd
    src/openglexample.d(413,5): Error: undefined identifier glBegin
    src/openglexample.d(418,9): Error: undefined identifier glVertex3f
    src/openglexample.d(419,9): Error: undefined identifier glVertex3f
    src/openglexample.d(420,9): Error: undefined identifier glVertex3f
    src/openglexample.d(422,9): Error: undefined identifier glVertex3f
    src/openglexample.d(425,5): Error: undefined identifier glEnd
    src/openglexample.d(427,5): Error: undefined identifier glNormal3f
    /usr/bin/dmd failed with exit code 1.

Clearly I'm not providing the right file, but what should the right file be?

Anyway, I could search a long time but clearly an example that doesn't work out of the box doesn't have much value and managing dependencies should be fixable so I think this should be fixed.

**Comment by TheCurle** [comment]
It looks like the update to DerelictGL 2.0.0 changed how the whole thing works.
Namely, the submodules are no longer publically importable.
You'd need to manually downgrade to a version of DlangUI that hard-requires <2.0.0, or manually edit the example file to work with the (practically) new library.

A pain, but considering the author is considering abandoning the project, i felt like some closure would be nice for you.

**Comment by GrimMaple** [comment]
I am going to close this, as the project moved on to bindbc. I have checked and, on my machine at least, it compiles and runs fine :) If the there are other issues with this build, please open another issue.
