### ISSUE TITLE
Is it possible to host a Winforms control in a Dlang UI?

### ISSUE THREAD

**Issue by DarkRiDDeR** [buggins/dlangui#590]
The thing is that I'd like to use some 3rd-party controls which are only offered as Winforms controls. Is there a way to host a winforms control in a Dlang UI window like how we can host Wpf controls in Winforms applications (and vice-versa)?

**Comment by harryisgamer** [comment]
Probably not, considering winforms is a .NET language (C# / VB.NET, etc...). I don't think D can use .NET libraries.
