### ISSUE TITLE
when build on debian bluster, error msg below

### ISSUE THREAD

**Issue by bitcenc-lab** [buggins/dlangui#595]
/usr/include/dmd/phobos/std/functional.d-mixin-215(215,23): Error: undefined identifier ascii in package std, perhaps add static import std.ascii;
/usr/include/dmd/phobos/std/algorithm/iteration.d(3718,28): Error: template instance `std.functional.F!(" a && (b == '_' || std.ascii.isAlphaNum(b)) ", "a", "b").binaryFun!(bool, dchar)` error instantiating

**Comment by buggins** [comment]
Is it fixed in recent version?

**Comment by GrimMaple** [comment]
I'm closing build related issues since we have a CI now.
