### ISSUE TITLE
Windows 10: lld-link: error: unknown directive: EXETYPE 

### ISSUE THREAD

**Issue by BoQsc** [buggins/dlangui#597]
### System information

- **dub version**: `dub --version
DUB version 1.17.0, built on Sep  1 2019`
- **OS Platform and distribution**:  Windows 10
- **compiler version** `dmd --version
DMD32 D Compiler v2.088.0-dirty`

### Bug Description
Today, I wanted to fetch/download and run one of the examples of dlangui.
They worked on my Linux machine. However here on Windows 10 I get linker error.

### How to reproduce?
Simply install dmd compiler on Windows 10.  
Open Command Prompt and run: 
1. `dub run dlangui` for dub to fetch/download the whole project.
2. and then `dub run dlangui:example1` to run the example from the downloaded project.

### Expected Behavior
A basic dlangui example should show up. However it do not.

### Logs
```
C:\Users\Juozas>dub run dlangui:example1
Building package dlangui:example1 in C:\Users\Juozas\AppData\Local\dub\packages\dlangui-0.9.182\dlangui\examples\example1\
Performing "debug" build using C:\D\dmd2\windows\bin\dmd.exe for x86_64.
derelict-util 3.0.0-beta.2: building configuration "library"...
derelict-ft 2.0.0-beta.5: building configuration "library"...
derelict-gl3 2.0.0-beta.8: building configuration "library"...
derelict-sdl2 3.0.0-beta.8: building configuration "derelict-sdl2-dynamic"...
dlangui 0.9.182: building configuration "default"...
AppData\Local\dub\packages\dlangui-0.9.182\dlangui\src\dlangui\dom\cssparser.d(86,18): Deprecation: union field intValue with default initialization 0 must be before field typeFlagId
AppData\Local\dub\packages\dlangui-0.9.182\dlangui\src\dlangui\dialogs\filedlg.d(377,54): Deprecation: function std.typecons.Nullable!(SysTime).Nullable.get_ is deprecated - Implicit conversion with alias Nullable.get this will be removed after 2.096. Please use .get explicitly.
AppData\Local\dub\packages\dlangui-0.9.182\dlangui\src\dlangui\dialogs\filedlg.d(377,63): Deprecation: function std.typecons.Nullable!(SysTime).Nullable.get_ is deprecated - Implicit conversion with alias Nullable.get this will be removed after 2.096. Please use .get explicitly.
AppData\Local\dub\packages\dlangui-0.9.182\dlangui\src\dlangui\dialogs\filedlg.d(377,73): Deprecation: function std.typecons.Nullable!(SysTime).Nullable.get_ is deprecated - Implicit conversion with alias Nullable.get this will be removed after 2.096. Please use .get explicitly.
AppData\Local\dub\packages\dlangui-0.9.182\dlangui\src\dlangui\dialogs\filedlg.d(377,81): Deprecation: function std.typecons.Nullable!(SysTime).Nullable.get_ is deprecated - Implicit conversion with alias Nullable.get this will be removed after 2.096. Please use .get explicitly.
AppData\Local\dub\packages\dlangui-0.9.182\dlangui\src\dlangui\dialogs\filedlg.d(377,90): Deprecation: function std.typecons.Nullable!(SysTime).Nullable.get_ is deprecated - Implicit conversion with alias Nullable.get this will be removed after 2.096. Please use .get explicitly.
AppData\Local\dub\packages\dlangui-0.9.182\dlangui\src\dlangui\widgets\editors.d(3447,9): Deprecation: foreach: loop index implicitly converted from size_t to int
AppData\Local\dub\packages\dlangui-0.9.182\dlangui\src\dlangui\widgets\editors.d(3797,21): Deprecation: foreach: loop index implicitly converted from size_t to int
dlangui:example1 0.9.182: building configuration "default"...
Linking...
lld-link: error: unknown directive: EXETYPE
Error: linker exited with status 1
C:\D\dmd2\windows\bin\dmd.exe failed with exit code 1.
```

**Comment by GrimMaple** [comment]
It is possible to fix this by removing the "sourceFiles-windows" entry in dub.json for example1. See my pr for details.

**Comment by BoQsc** [comment]
> It is possible to fix this by removing the "sourceFiles-windows" entry in dub.json for example1. See my pr for details.

It does allow to compile, build and run it.  
However, does not seem like this have been fixed.
Why is this issue closed. @buggins 

## Workaround in more details: 
1. Open `%LOCALAPPDATA%\dub\packages\dlangui-0.9.186\dlangui\examples\helloworld\dub.json` with a Text Editor.
**Example:**
   * C:\Users\BoQsc\AppData\Local\dub\packages\dlangui-0.9.186\dlangui\examples\helloworld\dub.json
2. Find and delete the whole line of `sourceFiles-windows` on line 12
 
   ![image](https://user-images.githubusercontent.com/21064622/125164293-27919e80-e19a-11eb-96f1-7732cf10fb74.png)
3. Rerun `dub run dlangui:helloworld`

![image](https://user-images.githubusercontent.com/21064622/125164427-d46c1b80-e19a-11eb-9810-7d9b4d3d513a.png)
