### ISSUE TITLE
Compilation on LDC 1.19.0

### ISSUE THREAD

**Issue by NotSpooky** [buggins/dlangui#602]
My project fails to compile using v0.9.182 with a deprecation on lists.d
Using the DigitalMars version code fixes it.

Didn't do a pull request because it might break with older versions of LDC

**Comment by janp20** [comment]
Project dead?? It would be a shame, this is a lot of good work.

**Comment by mvfranz** [comment]
> 
> 
> Project dead?? It would be a shame, this is a lot of good work.

I hope not.  I have been meaning to use the GUI for an application, but just have not had the time.

**Comment by GrimMaple** [comment]
I'm going to close this for now. There is a workflow to test against latest LDC. If any other build issues arise, please open a new Issue :)
