### ISSUE TITLE
Looking for new dlangui maintainer

### ISSUE THREAD

**Issue by buggins** [buggins/dlangui#608]
Since the project is mostly abandoned by author (me), I'm looking for kind people who wants to support it.

**Comment by drug007** [comment]
Probably the best way is to transfer the project to D community. Big thanks to you for your great job!

**Comment by GrimMaple** [comment]
Unfortunately I'm too busy with other stuff and could not become a full maintainer. But I am willing to provide help with looking over pull requests and maybe keeping this build-able on Windows.

**Comment by buggins** [comment]
I can grant repository privileges to several developers.

What is a procedure of transferring to D community?

**Comment by GrimMaple** [comment]
@buggins https://github.com/dlang-community/discussions#adoption-guidelines here are adoption guidlines

**Comment by drug007** [comment]
@buggins I've created organization dlangui, you can transfer dlangui there and let others to adopt the project to the D community.

**Comment by drug007** [comment]
@buggins also you can create the organization and add developers there. I'm in the same boat like GrimMaple but I understand the importance of dlangui to allocate some time to it.

**Comment by GrimMaple** [comment]
Bump. What's up?
@buggins what about the adoption? Will you create an issue in https://github.com/dlang-community/discussions/issues ? If you don't want to be bothered with this, I could do it, just say it!

**Comment by giaur500** [comment]
rip

**Comment by GrimMaple** [comment]
@buggins sorry for the ping, but I messaged you about taking over maintenance on habr. Any updates?

**Comment by Imperatorn** [comment]
Hello?

**Comment by ZILtoid1991** [comment]
I could take over. I have created a GUI subsystem for my own game engine, complete with a window layout editor.

My main issue is that I now work full time, and I barely can do my own projects.

**Comment by GrimMaple** [comment]
I'm gonna close this as this is no longer relevant :)
