### ISSUE TITLE
Compiler crashes on resources.d

### ISSUE THREAD

**Issue by Superbelko** [buggins/dlangui#616]
That's a bug.

Cause - this debug statement in class ctor:
https://github.com/buggins/dlangui/blob/86baf487e7773cddcd3630ef875c9e7c7ff442b8/src/dlangui/graphics/resources.d#L1576

Workaround:
remove `debug` or comment out this line

(edit)
Bugzilla entry:
https://issues.dlang.org/show_bug.cgi?id=22365

**Comment by GrimMaple** [comment]
This appears to be fixed in recent versions of DMD
