### ISSUE TITLE
Error: unable to read module `icontheme`

### ISSUE THREAD

**Issue by ammatwain** [buggins/dlangui#640]
Thanks for your valuable work.
Ammatwain

**Comment by GrimMaple** [comment]
so is this all right now?
I saw a bunch of failed autotests, but I couldn't reproduce on my machines

**Comment by leotada** [comment]
I'm having this error too. Maybe you can explain please @ammatwain

**Comment by leotada** [comment]
Thanks @GrimMaple . I just notice that building an example from master.
