### ISSUE TITLE
[Linux example1] OpenGL tab seems to grey out the UI

### ISSUE THREAD

**Issue by Spirrwell** [buggins/dlangui#647]
Hello!

This issue only happens on master. The latest release seems to be fine. You can see in one of the screenshots that all the elements appear inactive. When the application first starts up, it's fine. Clicking on the OpenGL tab makes everything appear in this inactive state, though I can still interact with things.

I am running on Fedora 37, under the GNOME DE. I tried with both X11 and Wayland, same result. This only happens on Linux from my testing.

![Screenshot from 2023-01-09 09-56-33](https://user-images.githubusercontent.com/8671884/211341290-6936b65a-9f32-4469-9a76-31a5dc8961f0.png)

![image](https://user-images.githubusercontent.com/8671884/211341465-dfa164da-2b69-4978-ba1e-859086cf4b3d.png)

**Comment by GrimMaple** [comment]
Unfortunately, I can't reproduce on KDE. Any build options by any chance?
![image](https://user-images.githubusercontent.com/10130860/211374778-9159c1d0-3115-4417-b6b2-6a111aabc276.png)

**Comment by GrimMaple** [comment]
I'm running Majaro KDE with Intel integrated video card. I also checked a release build, and it works fine as well.

It might be either a gnome-related issue, either a video card related issue. I'll try setting up a gnome DE in a VM to test, but some time later.

**Comment by GrimMaple** [comment]
> It appears to be related to this: https://github.com/buggins/dlangui/blob/master/examples/example1/src/widgets/opengl.d#L167
> 
> `checkgl!glEnable(GL_POLYGON_SMOOTH);`
> 
> This is what causes that issue. If I add a corresponding `checkgl!glDisable(GL_POLYGON_SMOOTH);` at the end, the issue is then only limited to the cube and not the whole application.
> 
> I don't know anything about GL_POLYGON_SMOOTH or why it's broken for me, but I would definitely at least disable any enabled features at the end of this function so that they don't affect the whole application.

Feel free to PR it, I'd be glad to accept it :) On the other hand, it could be wise to not enable `GL_POLYGON_SMOOTH`, as there is no need for it. AFAIK, it enables multisampling, which is currently unsupported by this example anyway.

So, if removing `GL_POLYGON_SMOOTH` fixes everything for you, please PR it :)

**Comment by Spirrwell** [comment]
As far as multisampling is concerned, is this what the call to `checkgl!glEnable(GL_MULTISAMPLE);` is for? So that should be removed as well if GL_POLYGON_SMOOTH is removed?

**Comment by GrimMaple** [comment]
> As far as multisampling is concerned, is this what the call to `checkgl!glEnable(GL_MULTISAMPLE);` is for? So that should be removed as well if GL_POLYGON_SMOOTH is removed?

Yes, that could be removed too. Just check that it does fix everything for you c:

**Comment by Spirrwell** [comment]
Alrighty, PR is open. This definitely does fix my issues. From what I've read, GL_POLYGON_SMOOTH is apparently not very compatible with depth testing.

**Comment by GrimMaple** [comment]
Yea, I'm gonna close tis for now if it's fixed :)
