### ISSUE TITLE
Icons are broken on linux

### ISSUE THREAD

**Issue by GrimMaple** [buggins/dlangui#648]

**Comment by GrimMaple** [comment]
> If you mean that the `Icons` tab doesn't show icons in example1 - it's probably due to using the .svg-only icon theme. It should show icons if the current icon theme has .png images. It can't be fixed until dlangui gets svg rendering support.
> 
> Overall the whole mechanism is probably not used in any dlangui app. The example was part of my plan to let dlangui use icons native for the environment.

Actually, since I switched to `arsd.image` in https://github.com/buggins/dlangui/commit/663b7dfd739c4ad84afd6f8b90c9e71237be37e5 , `dlangui` now supports svg. Or at least it could if a proper loading mechanism is written.
Now, I don't know much about handling svg's, so if anyone does know -- please PR it.

**Comment by FreeSlave** [comment]
I made PR
