### ISSUE TITLE
Can not load freetype library

### ISSUE THREAD

**Issue by boolkaDev** [buggins/dlangui#665]
I tried to run example code and I got this error in terminal
2023-07-15 18:24:13.725 E  bindbc-freetype: cannot load freetype shared library: bindbc-freetype unable to find suitable library, ft26 minimum required
object.Exception@../../../.dub/packages/dlangui/0.10.4/dlangui/src/dlangui/graphics/ftfonts.d(599): Cannot load freetype library
----------------
../../../.dub/packages/dlangui/0.10.4/dlangui/src/dlangui/graphics/ftfonts.d:599 dlangui.graphics.ftfonts.FreeTypeFontManager dlangui.graphics.ftfonts.FreeTypeFontManager.__ctor() [0x10058543b]
../../../.dub/packages/dlangui/0.10.4/dlangui/src/dlangui/platforms/common/startup.d:236 initFontManager [0x1005c3c9a]
../../../.dub/packages/dlangui/0.10.4/dlangui/src/dlangui/platforms/sdl/sdlapp.d:1638 int dlangui.platforms.sdl.sdlapp.sdlmain(immutable(char)[][]) [0x1005c9643]
../../../.dub/packages/dlangui/0.10.4/dlangui/src/dlangui/platforms/sdl/sdlapp.d:1604 DLANGUImain [0x1005c94cb]
../../../.dub/packages/dlangui/0.10.4/dlangui/src/dlangui/platforms/common/platform.d:2130 _Dmain [0x10044f2cf]
2023-07-15 18:24:13.738 D  Destroying font manager
Error Program exited with code 1
How can I fix this issue?

**Comment by GrimMaple** [comment]
Hi! Do you have freetype installed on your system? If yes, what version?
Also, what is your OS?

**Comment by bagomot** [comment]
As a temporary solution: [download the binary of the new version of the library](https://download.savannah.gnu.org/releases/freetype/) and replace it next to your executable.

**Comment by Marty-Stu** [comment]
Hi.

I had a similar problem.
It happened when I had only `libfreetype6` installed on `Debian`:
```
sudo apt-get install libfreetype6
```
This is the solution that worked for me:
```
sudo apt-get install libfreetype6 libfreetype6-dev
```
