### ISSUE TITLE
Question about CSS

### ISSUE THREAD

**Issue by Yorizuka** [buggins/dlangui#666]
I am currently reading the dlangui source code trying to understand the code base.

I have a question about the CSS functionality, so far in all the examples and the included default styling is done via android like XML, I have not seen any CSS files in the repo. But in the source code of dlangui there is a CSS parser.

What is the state of the CSS parser?
Is it an alternative syntax for ingesting the same data as the XML based styling?

**Comment by Yorizuka** [comment]
Well I ended up removing:
1. core/css.d
2. core/cssparser.d
3. core/dom.d
4. dom/cssparser.d
5. dom/encoding.d

after doing so everything seems to still work exactly the same way. So my hunch is that its unfinished & unused code.

**Comment by GrimMaple** [comment]
PRs are more than welcome, though I'm unsure if it actually doesn't break anything. More testing would be needed. Good for us that I have a lot of dlangui projects to test on :)
