### ISSUE TITLE
OSX support improvements: library paths

### ISSUE THREAD

**Issue by buggins** [buggins/dlangui#681]
Going to improve OSX support.
This is part 1 - fixing of deps library paths.

Trying to build dlangui app on Mac OSX arm64 (m3).
It looks like dmd does not have arm64 support.
Installed ldc2, dub, freetype and sdl using homebrew.
Now I'm able to build dlangui apps with dub, but it looks like bindbc loaders cannot find libraries installed with homebrew.
Workaround is to set DYLD path:

```DYLD_LIBRARY_PATH=/opt/homebrew/lib```

Created PR for bindbc-freetype

https://github.com/BindBC/bindbc-freetype/pull/14

Not sure if it's proper way of fixing, or it's better to do some change in common bindbc code.

UPD: bindbc-sdl has homebrew path in the list of paths for OSX

**Comment by buggins** [comment]
Upgraded bindbc dependencies to latest version - didn't help to resolve this issue.
bindbc-freetype actually had build errors and some other issues.
Prepared PR to fix it: https://github.com/BindBC/bindbc-freetype/pull/14

**Comment by buggins** [comment]
fixed in v0.10.6

**Comment by GrimMaple** [comment]
It seems that in the meantime bindbc-freetype broke dlangui on windows. Very sad times :(
Will investigate later
