### ISSUE TITLE
TextWidget.click is not firing

### ISSUE THREAD

**Issue by whitebyte** [buggins/dlangui#686]
```d
import std.stdio : writeln;
import dlangui;

mixin APP_ENTRY_POINT;

extern (C) int UIAppMain(string[] args) {
    Window window = Platform.instance.createWindow("", null);

    auto w = new TextWidget();
    w.text = "Test 123";
    w.click = delegate(Widget w) {
        writeln(w.text);
        return true;
    };

    window.mainWidget = w;
    window.show();

    return Platform.instance.enterMessageLoop();
}
```

When I run this example and click the widget, nothing happens. If we replace `TextWidget` with `Button` it works as intended. I'm looking here http://buggins.github.io/dlangui/ddox/dlangui/widgets/controls/TextWidget.html and I have an impression that `TextWidget` should be clickable. Am I missing something here?

**Comment by whitebyte** [comment]
Also for some reason `TextWidget` won't appear until the main window resize, but I guess it's a separate issue

**Comment by GrimMaple** [comment]
> If we replace `TextWidget` with `Button` it works as intended. I'm looking here http://buggins.github.io/dlangui/ddox/dlangui/widgets/controls/TextWidget.html and I have an impression that `TextWidget` should be clickable. Am I missing something here?

Hi! I've looked into the source code, and clicking is actually disabled for `TextWidget`. Actually-actually, clicking has to be explicitly enabled for a widget, which `TextWidget` doesn't do, so it never gets to processing clicks. I don't know if it's a bug or intended behavior, and I don't know if clicking a `TextWidget` should be allowed :)

> Also for some reason `TextWidget` won't appear until the main window resize, but I guess it's a separate issue

I have tested this on Windows 11 and it works fine - `TextWidget` is displayed as intended. Can you tell me what OS do you use and what platform (x11, SDL, etc)?

**Comment by whitebyte** [comment]
Indeed, setting `clickable = true` did the trick. 
>I don't know if clicking a TextWidget should be allowed :)
I see no reason why  not?

> Can you tell me what OS do you use and what platform (x11, SDL, etc)?
It's Linux. I guess it's SDL

**Comment by whitebyte** [comment]
Completely forgot about this ticket and just got bitten by it again.
There are lots of scenarios when a text widget needs to be clickable. In the maintainers agree that this is indeed a bug, I can open a PR

**Comment by GrimMaple** [comment]
> Completely forgot about this ticket and just got bitten by it again. There are lots of scenarios when a text widget needs to be clickable. In the maintainers agree that this is indeed a bug, I can open a PR

Well, I disagree that it's a bug. All widgets are unclickable by default, and clicking has to be enabled explicitly. Like so:

```d
class ClickableText : TextWidget
{
    this(string ID = null)
    {
        super(ID);
        clickable = true;
    }
}
```
I will be more than glad to merge in a `ClickableText` widget though :)

**Comment by whitebyte** [comment]
>All widgets are unclickable by default, and clicking has to be enabled explicitly

Indeed. That wasn't obvious for me. Let's just close this one then
