### ISSUE TITLE
Widget.child throws if there is no child

### ISSUE THREAD

**Issue by whitebyte** [buggins/dlangui#691]
```d
auto widget = parent.childById("nonexistent"); // returns null
auto widget2 =parent.child(1000); // throws exception
```
Expected behavior: `.child(x)` should return `null` if there is no child with such index (or no children at all).
I can open a PR if maintainers agree

**Comment by GrimMaple** [comment]
According to [this](https://github.com/buggins/dlangui/blob/3c38f32e79336326e6213ea45cc5a56f57fb8670/src/dlangui/widgets/widget.d#L1600C5-L1600C58) the base class already returns null. I think that "return null" is intended behavior, so I don't mind such PR at all :)
If you're at it -- please make sure that it's consistent across all subclasses
