### ISSUE TITLE
Scrollbars should only appear when needed.

### ISSUE THREAD

**Issue by Freakazo** [buggins/dlangui#70]
Currently both the vertical and horizontal scrollbars for widgets such as logwidget displays all the time, even when they are not needed. This takes up a lot of unnecessary space.

**Comment by buggins** [comment]
There is already setting for scrollbar - visible, invisible, auto.
But their usage is not implemented.

**Comment by drug007** [comment]
If scrollbar settings aren't implemented why you closed the issue? Does it duplicate another one?
