### ISSUE TITLE
GUI is blurry when using retina displays

### ISSUE THREAD

**Issue by Kapps** [buggins/dlangui#72]
Due to a lack of high DPI support, using a high DPI screen results in the library being very blurry and looking ugly as a result.
To get a high DPI window using SDL, one can add SDL_WINDOW_ALLOW_HIGHDPI to the window flags when creating a window.
On Windows, if not using SDL, you can use SetProcessDPIAware(), or add the following to the app manifest file:
````
  <asmv3:application>
    <asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
      <dpiAware>true</dpiAware>
    </asmv3:windowsSettings>
  </asmv3:application>
````

The problem is that (at least on OSX, possibly others), aside from the layouts not being properly positioned, mouse clicks are registered in the wrong location as well.

**Comment by buggins** [comment]
Added SDL_WINDOW_ALLOW_HIGHDPI flag for SDL windows.
Could you please test changes? Unfortunately I don't have mac.

**Comment by buggins** [comment]
Does it look blurry on some windows systems, too?

**Comment by Kapps** [comment]
Unfortunately making high DPI work properly requires more than just setting the window to be high DPI. As mentioned above, one large issue is that mouse presses appear to register in the wrong locations or the UI behaves oddly. The UI ends up taking only the top left 1/4 of the screen, while the rest of the screen is white, but mouse presses are registered where they previously were(?, or at least in the wrong location). It also needs to be something that's opt-in, as anything relying on absolute positions will not work well once DPI scaling is applied, programs have to be developed using relative layouts for the most part.

**Comment by buggins** [comment]
For DLangUI to work properly, coordinates of mouse events must match pixels.

I found discussion of similar problem

http://forums.libsdl.org/viewtopic.php?t=9576&sid=090b706304f1829218c9c0f6887cce86


Dlangui doesn't use absolute (fixed) positioning.
UI scaling is possible. E.g. increasing of font size. Resources for different DPI are planned (e.g. to have bigger icons in high res)

**Comment by buggins** [comment]
I've submitted fix to use SDL_GL_GetDrawableSize for high dpi.
I believe it should fix image size issue, but not sure if mouse positioning is working properly.
Could you please check?

**Comment by buggins** [comment]
Submitted additional fix to correct mouse coordinates. Should work ok now.
Please confirm.
I cannot test myself since I have no mac.

**Comment by Kapps** [comment]
Looks like mouse coordinates are fixed (at least on OSX, can't test Windows atm, but should be the same I'd imagine).

The remaining issues for high DPI support would be scaling and that the viewport seems to only render to the unscaled location. Example with 2x DPI scaling: http://i.imgur.com/bjynrro.png
I tried taking a look at layout.d but wasn't able to figure out how to get it scaling / rendering properly.

**Comment by buggins** [comment]
Do you see log message like
            Log.d("SDL_GL_GetDrawableSize returned ", w, "x", h, " while resize event reports ", width, "x", height);
What are sizes reported in this message?

**Comment by buggins** [comment]
Does mouse work as if image would be drawn on full window?
E.g. when you click on white area, actually click on some control is processed?

**Comment by buggins** [comment]
Doesn't image get fixed if you try to resize window?

**Comment by buggins** [comment]
I've submitted additional fix which can probably resolve issue (should work if resize helps).

**Comment by Kapps** [comment]
The sizes reported are 1400x1000 for drawable, 700x500 for resize event.
The mouse works properly now, it used to work as if the image was drawn on a full window before you fixed it in commit e8f2057. 
Resizing the window has no effect, the image remains in only the top left quarter of the screen (double DPI, therefore half width half height). I notice though that there are multiple resize events, one with the scaled resolution (1400x992) followed by a second one with the unscaled resolution (700x496).
I took a look to see if I could find what was causing that, and I'm guessing it's due to most other methods still using SDL_GetWindowSize instead of SDL_GL_GetDrawableSize. After changing void fixSize() and void redraw() to use SDL_GL_GetDrawableSize instead of SDL_GetWindowSize, it no longer renders only to the top 1/4 of the screen, and mouse coordinates still seem to work properly.

The diff is just:
````
--- a/src/dlangui/platforms/sdl/sdlapp.d
+++ b/src/dlangui/platforms/sdl/sdlapp.d
@@ -172,7 +172,7 @@ class SDLWindow : Window {
     void fixSize() {
         int w = 0;
         int h = 0;
-        SDL_GetWindowSize(_win, &w, &h);
+        SDL_GL_GetDrawableSize(_win, &w, &h);
         doResize(w, h);
     }
 
@@ -365,7 +365,7 @@ class SDLWindow : Window {
         //Log.e("Widget instance count in SDLWindow.redraw: ", Widget.instanceCount());
         // check if size has been changed
         int w, h;
-        SDL_GetWindowSize(_win, &w, &h);
+        SDL_GL_GetDrawableSize(_win, &w, &h);
         onResize(w, h);
 
                if (_enableOpengl) {
````
I'm not sure if the fixSize part is actually necessary or not, adding it to the redraw() method is what fixed it. It seems to work without the fixSize change, but I'm not sure when that actually gets used.

This is what it looks like now:
![screen shot 2015-03-11 at 9 50 52 am](https://cloud.githubusercontent.com/assets/1259333/6600260/36d67514-c7d4-11e4-8382-33fa31aec091.png)

At this point the main things necessary would be things like font scaling in order to have nice high DPI support. Simply doubling the font size in FontFileItem.get(size) (though the proper solution would likely be to multiply by DPI scaling factor) results in:
![screen shot 2015-03-11 at 9 55 55 am](https://cloud.githubusercontent.com/assets/1259333/6600427/1e4011f8-c7d5-11e4-96d6-9f90d940200d.png)

Which seems to work well, respond to the mouse appropriately still, and scales nicely at least in example1. The tetris app has an issue where every block is 1x1 size. A brief test of dlangide shows it seems to work okay as well:
![screen shot 2015-03-11 at 10 07 51 am](https://cloud.githubusercontent.com/assets/1259333/6600666/8d735af2-c7d6-11e4-9a21-f316c2cd0465.png)

**Comment by Kapps** [comment]
On Windows, we still need to use the SetProcessDPIAware function (or the newer SetProcessDPIAwareness, but that's only supported on Windows 8.1 and higher). The problem is that D's version of user32.lib that's bundled with DMD is too old. A simple workaround is to load it manually:

In winapp.d:
````
private alias SetProcessDPIAwareFunc = int function();
````
And then to call it (over in WinMain):
````
@@ -868,6 +868,10 @@ int DLANGUIWinMain(void* hInstance, void* hPrevInstance,
     try
     {
         Runtime.initialize();
+        auto ulib = LoadLibraryA("user32.dll");
+        auto setDpiFunc = cast(SetProcessDPIAwareFunc)GetProcAddress(ulib, "SetProcessDPIAware");
+        if(setDpiFunc) // Should never fail, but just in case...
+            setDpiFunc();
````

Combined with doubling the font size in win32fonts.d (again, not a proper solution, just for testing), it seems to work okay besides that the initial window is created too small.
![screen shot 2015-03-11 at 11 41 07 am](https://cloud.githubusercontent.com/assets/1259333/6602794/8f17c7d2-c7e3-11e4-9f78-20cc3a460de6.png)
Or when resized:
![screen shot 2015-03-11 at 11 41 40 am](https://cloud.githubusercontent.com/assets/1259333/6602801/9cdacc98-c7e3-11e4-9d0d-1009a3489c4a.png)

**Comment by buggins** [comment]
I hope new fix resolves this issue.

For specifying of font size in themes, pt support is implemented (e.g. fontSize="9pt")

For SDL app, screen DPI is just set to 96 for non-scaled and 96*scale(96*2) for Retina.

TODO: support separate drawable resources for different resolutions.

**Comment by Kapps** [comment]
Almost! On Windows, it seems to work nicely (at least using winapp.d, not sure about sdlapp.d, but I'd imagine it should be the same).

On OSX, the SCREEN_DPI value is set only after the layout is, causing the fonts to all be too small unless the layout is manually reloaded, as the points are calculated based off of the old DPI. Unfortunately by the time there's an SDL_Window to calculate the DPI with, it seems to be too late as the layouts were already loaded and points already converted to pixels. Not sure of an ideal solution for that, either reloading the layout after the window is created, deferring it until then, converting every time / storing points instead of pixels, or using an external API to calculate DPI (I'm not sure if any exist that we can access). 

Also, I found that if hardcoding SCREEN_DPI = 96 * 2 before the window is created, the window is created too large on OSX. It seems the OS already scales it on OSX (but not on Windows).

**Comment by buggins** [comment]
Submitted fix to hold point sizes in styles, instead of converting to px while load.
I hope now problem should be fixed.

**Comment by Kapps** [comment]
This fix unfortunately made it so that the UI just never scales, even in Windows and even after reloading the theme. I've been taking a look seeing if I can figure out why, but haven't had any luck so far.

**Comment by buggins** [comment]
Must be fixed now. Could someone please verify?

**Comment by Kapps** [comment]
Fixed!

At least with dlangui:example1, I tried dlangide but I get a whole bunch of [errors](http://pastie.org/private/yeo1oljnybetvay7xxp2w) related to missing resources for high-dpi. I think the actual issue itself is fixed though, high DPI support seems to work nicely so far with no effort from the user, which is awesome.

**Comment by buggins** [comment]
dlangui build is fixed

**Comment by Kapps** [comment]
Works now, awesome. I think this issue can be closed now, high DPI support seems to work well, which is a really nice benefit to using dlangui.
