### ISSUE TITLE
Everything is tiny on OSX Retina display

### ISSUE THREAD

**Issue by kingsleyh** [buggins/dlangui#76]
When I did get over the black screen issue by using the code Kapps pasted I get a working screen however its very tiny - see screenshot:

![buttons_-_dlangui_example_1](https://cloud.githubusercontent.com/assets/103770/6764611/baa363fa-cfb0-11e4-875b-5f6dbcd66261.png)

**Comment by kingsleyh** [comment]
Here is another screenshot which highlights the difference more

![buttons_-_dlangui_example_1_and_dlangui_ _example1_ _80x24_and_buggins_dlangui_and_microsoft_word](https://cloud.githubusercontent.com/assets/103770/6764620/1f3029ca-cfb1-11e4-825d-b97437b0a459.png)

**Comment by Kapps** [comment]
This is part of a larger issue #72 to get high DPI screens working nicely with automatic scaling.

**Comment by buggins** [comment]
Must be fixed now. Could someone please verify?

**Comment by kingsleyh** [comment]
Yay this mostly works now for me on OS X Yosemite with Retina display
	
The text in the compiler log is still very tiny as are the icons - but most of the other text is the right size

**Comment by kingsleyh** [comment]
see screenshot of dlangide

![home_-_dlangide_and_dlangide_ _dlangide_ _80x24](https://cloud.githubusercontent.com/assets/103770/6776018/4b3e5bfa-d131-11e4-9148-339595b8d633.png)

**Comment by buggins** [comment]
Submitted fix for log window font size.
DPI aware icons support is in progress.

**Comment by buggins** [comment]
HDPI icons added

**Comment by kingsleyh** [comment]
just pulled from master and error with icons:

../../.dub/packages/dlangui-master/src/dlangui/graphics/resources.d(152): Error: file "hdpi_document-save-as.png" cannot be found or not in a path specified with -J
../../.dub/packages/dlangui-master/src/dlangui/graphics/resources.d(153): Error: data.length cannot be evaluated at compile time
../../.dub/packages/dlangui-master/src/dlangui/graphics/resources.d(166): Error: template instance dlangui.graphics.resources.embedResource!"res/hdpi/hdpi_document-save-as.png" error instantiating
FAIL .dub/build/application-debug-posix.osx-x86_64-dmd_2066-807DE7B453597C44BA38F1B5D5AE036E/ dlangide executable
Error executing command run: dmd failed with exit code 1.

**Comment by buggins** [comment]
Sorry. Forgot to update dub.json
fixed
