### ISSUE TITLE
Redundant 'const'

### ISSUE THREAD

**Issue by joelcnz** [buggins/dlangui#79]
This is with DMD 2.067

../../../../.dub/packages/gl3n-1.0.0/gl3n/linalg.d(581): Error: redundant attribute 'const'
../../../../.dub/packages/gl3n-1.0.0/gl3n/linalg.d(2465): Error: redundant attribute 'const'

I tried to fix it my self, but couldn't find the source file.

**Comment by buggins** [comment]
it's in dependency package, gl3n
on gl3n ~master it's fixed.

try update dependencies:

dub upgrade --force-remove
dub build --force

Let me know if problem still exists after upgrade

**Comment by joelcnz** [comment]
I works again.
