### ISSUE TITLE
Blank window

### ISSUE THREAD

**Issue by Damani** [buggins/dlangui#81]
Blank window when using default configuration
![dlangide](https://cloud.githubusercontent.com/assets/545324/6896348/0d6ab338-d6f3-11e4-821b-c3e60a54eee1.png)
Same with my own projects
SDL configuration work ok
OS: Windows 8.1
https://www.dropbox.com/s/wnub4m13t3gu307/ui.log?dl=0

**Comment by fabsi88** [comment]
Hi @buggins - this is the same problem as I described at gitter. If you still need further logs I will upload them. Just let me now.

**Comment by buggins** [comment]
Can you run debug version? dub run build=debug
Release version shows only errors in logs. Debug is more verbose.
It looks like shaders creation was failed.

**Comment by Damani** [comment]
dub run --build=debug
https://www.dropbox.com/s/560s8rzf7rwvcdr/ui_debug.log?dl=0

**Comment by fabsi88** [comment]
Just in case u need more information here is my (debug build) log:
https://www.dropbox.com/s/ixx5b2blmvx3neu/ui.7z?dl=0

**Comment by buggins** [comment]
I've submitted fix which probably should fix this issue.
Could you please check?

**Comment by Damani** [comment]
Checked, works ok

**Comment by buggins** [comment]
Thank you!
