### ISSUE TITLE
libfreetype-6.dll depends on MSVCR120.dll

### ISSUE THREAD

**Issue by thedeemon** [buggins/dlangui#86]
When running example1 a window pops up saying about inability to run because this MS VC runtime DLL is missing (I don't have a recent Visual Studio). Then the example1 actually runs, using fallback to Win32 for fonts.

Older version (20 commits earlier) ran without such pop-up windows, although also using Win32 for fonts, being unable to load the freetype lib.

I'm using Win8 and DMD 2.067, dub 0.9.23.

**Comment by buggins** [comment]
I've rebuilt freetype dlls with statically linked runtime.
Now issue should be fixed.
Please confirm.

As well, could you please check if 64 bit version is working as well? (--arch=x86_64)

**Comment by thedeemon** [comment]
I affirm, the issue is fixed, now the example (32-bit) runs without such messages, no complaints in ui.log and text is looking a bit different now.

x86_64 version builds fine but the app crashes when I try to run it (release version does some access violation). I'll try building and examining x64 debug version..

**Comment by buggins** [comment]
same for me - release version x64 crashes. Will try to investigate it

**Comment by buggins** [comment]
x86_64 release build crashes on glUseProgram
Very strange.
