### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by joelcnz** [buggins/dlangui#88]
Could there be a lot of small examples? I can't get started. Like, the only thing I can do is change the text in the Hello World one.

**Comment by buggins** [comment]
Did you check examples directory?
examples/example1 contains samples of most of widgets.
If you can explain what is unclear, I could try to write more examples or create some tutorials

**Comment by buggins** [comment]
examples/helloworld has been modified recently, and uses DML markup to create non-trivial UI layout.

**Comment by buggins** [comment]
I'm writing first tutorial on DlangUI Wiki: https://github.com/buggins/dlangui/wiki/Getting-Started

**Comment by buggins** [comment]
Some examples source code: https://github.com/buggins/dlangui-examples

**Comment by joelcnz** [comment]
Thanks for your replies, buggins.

**Comment by joelcnz** [comment]
Yes, I looked at the examples. I think I want mainly small examples (but whole programs) of different things, like single line and multiline text box, drop down selection. I couldn't figure out multiline text box from the big example file.

**Comment by buggins** [comment]
Ok. Next examples will be for EditLine, EditBox, ComboBox

**Comment by joelcnz** [comment]
Ok, cool, thanks.

**Comment by buggins** [comment]
DML based ComboBox and EditLine examples are added on https://github.com/buggins/dlangui-examples (controls directory)
