### ISSUE TITLE
Example from getting started is not linking

### ISSUE THREAD

**Issue by myromeu** [buggins/dlangui#89]
Target gl3n 1.0.1 is up to date. Use --force to rebuild.
Target dlib 0.5.2 is up to date. Use --force to rebuild.
Target derelict-util 1.9.1 is up to date. Use --force to rebuild.
Target derelict-ft 1.0.2 is up to date. Use --force to rebuild.
Target derelict-sdl2 1.9.5 is up to date. Use --force to rebuild.
Target derelict-gl3 1.0.12 is up to date. Use --force to rebuild.
Target dlangui 0.6.11 is up to date. Use --force to rebuild.
Building gui ~master configuration "application", build type debug.
Compiling using dmd...
Linking...
.dub/build/application-debug-linux.posix-x86_64-dmd_2067-D02A8FCBE930B5F392985AB46B1476E1/gui.o: In function `_Dmain':
/home/hasher/d/gui/../../.dub/packages/dlangui-0.6.11/src/dlangui/platforms/common/platform.d:1395: undefined reference to `_D7dlangui9platforms6common8platform11DLANGUImainFAAyaZi'
collect2: error: ld returned 1 exit status
--- errorlevel 1
FAIL .dub/build/application-debug-linux.posix-x86_64-dmd_2067-D02A8FCBE930B5F392985AB46B1476E1/ gui executable
Error executing command run: dmd failed with exit code 1.

**Comment by buggins** [comment]
try `dub upgrade --force-remove` followed by `dub build --force`

**Comment by buggins** [comment]
Assuming issue is fixed
