### ISSUE TITLE
Failed to start helloworld.

### ISSUE THREAD

**Issue by azurenote** [buggins/dlangui#90]
$ dub build --force
Building gl3n 1.0.1 configuration "library", build type debug.
Running dmd...
Building dlib ~master configuration "library", build type debug.
Running dmd...
Building derelict-util 1.9.1 configuration "library", build type debug.
Running dmd...
Building derelict-ft 1.0.2 configuration "library", build type debug.
Running dmd...
Building derelict-sdl2 1.9.5 configuration "library", build type debug.
Running dmd...
Building derelict-gl3 1.0.12 configuration "library", build type debug.
Running dmd...
Building dlangui 0.6.21 configuration "default", build type debug.
Running dmd...
Building helloworld ~master configuration "application", build type debug.
Compiling using dmd...
Linking...

$ dub run
Target gl3n 1.0.1 is up to date. Use --force to rebuild.
Target dlib ~master is up to date. Use --force to rebuild.
Target derelict-util 1.9.1 is up to date. Use --force to rebuild.
Target derelict-ft 1.0.2 is up to date. Use --force to rebuild.
Target derelict-sdl2 1.9.5 is up to date. Use --force to rebuild.
Target derelict-gl3 1.0.12 is up to date. Use --force to rebuild.
Target dlangui 0.6.21 is up to date. Use --force to rebuild.
Target helloworld ~master is up to date. Use --force to rebuild.
Running ./bin/helloworld 
Error executing command run:
Program exited with code -11

---------
I've tried in centos6. but don't know what's problem.

Also tried  dub upgrade --force-remove but doesn't help.

What should I do?

Thanks.

**Comment by buggins** [comment]
Probably, freetype initialization is failed. Not sure why there is no error message.
Let me check and add more logging.
BTW, what is fonts location on centos?

**Comment by buggins** [comment]
I have centos 5 box. Let me try it.

**Comment by azurenote** [comment]
Sorry for my late response.
You may know already, default location is /usr/share/fonts.

**Comment by buggins** [comment]
Implemented FontConfig support.
Could you please check if it resolves your problem?

**Comment by azurenote** [comment]
The problem isn't solved. But now, thanks for exception log, I can sure the problem is in derelict or freetype.

I've tried simple code to check freetype itself could be loaded or not :

import derelict.freetype.ft;
void main() { DerelictFT.load(); }

and result is same with helloworld:
derelict.util.exception.SymbolLoadException@../../../.dub/packages/derelict-util-1.9.1/source/derelict/util/exception.d(35): Failed to load symbol FT_Reference_Face from shared library libfreetype.so.6


Well, I don't know what's problem, let me check my system.

**Comment by buggins** [comment]
It looks like you have older version of FreeType on your system than Derelict_FT supports.
Need to check if it's possible to add support of older versions to DerelictFT
If won't work, I can just copy current DerelictFT code to dlangui and remove all unused functions.

**Comment by buggins** [comment]
FT_Reference_Face is added to freetype 2.4.2
What version of FreeType do you have on your system? Could you please check?

**Comment by azurenote** [comment]
There has been libfreetype 2.3 in my system and I've updated to 2.5.5 but faced new problem with SDL..

and installed SDL2 from source.

dub build --force
OK
dub run

...
2015-05-10 23:31:16.331 I  FontConfig: 244 font files registered in 12ms
2015-05-10 23:31:16.331 D  Creating default theme
2015-05-10 23:31:16.333 E  Cannot init SDL2
$

:(

Sorry I don't have enough time to test the lib but will continue soon.

**Comment by hdon** [comment]
>  If won't work, I can just copy current DerelictFT code to dlangui and remove all unused functions.

Derelict has a feature specifically to handle this situation:

https://github.com/DerelictOrg/DerelictUtil/blob/master/source/derelict/util/sharedlib.d#L219-L235

https://github.com/DerelictOrg/DerelictUtil/wiki/DerelictUtil-for-Users#selective-symbol-loading

**Comment by buggins** [comment]
Fixed for Freetype

**Comment by buggins** [comment]
Fixed old SDL2 versions support.
