### ISSUE TITLE
A bug in the example of Tetris

### ISSUE THREAD

**Issue by DennisMRitchie** [buggins/dlangui#94]
When I put the stick vertically into the bottom right corner:
![dlangui_tetris_bug 0](https://cloud.githubusercontent.com/assets/12628332/8047442/15a24150-0e4e-11e5-9809-46a782c133b9.png)
After that there was a bug:
![dlangui_tetris_bug 2](https://cloud.githubusercontent.com/assets/12628332/8047261/92db97a0-0e4b-11e5-9e7d-eb37f23b253f.png)
![dlangui_tetris_bug 1](https://cloud.githubusercontent.com/assets/12628332/8047260/92d1da8a-0e4b-11e5-9cea-172f8fac759d.png)

**Comment by buggins** [comment]
Fixed
