### ISSUE TITLE
Window.close() behavior in Windows

### ISSUE THREAD

**Issue by sentenzo** [buggins/dlangui#95]
Calling this method closes the window only when something from this list happen:
* mouse pointer leaves the window
* right mouse button click
* any key pressed (excluding <kbd>Enter</kbd> and <kbd>Space</kbd>)
* ... maybe something else 

You can use **dlangui:example1** for replay (*File->Exit*).

In Linux `Window.close()` closes window immediately. So, probably, this behaviour is Windows-only.

I tried this

    window.onCanClose =  delegate bool() { return true; };

and this

    window.dispatchKeyEvent(
        new KeyEvent(
            KeyAction.KeyDown, KeyFlag.Shift, KeyCode.KEY_M
    ));

with no effect.

So I can only use some terrible hacks, like

    version(Windows) { 
        window = null;
        window.update(true);
    }

to make main window close immediately in Windows.

**Comment by buggins** [comment]
Fixed.
