### ISSUE TITLE
huge memory occupation on Windows

### ISSUE THREAD

**Issue by timepp** [buggins/dlangui#96]
The minimal sample program in dub page takes ~90MB.

**Comment by buggins** [comment]
I see this behavior in OpenGL mode.
Win32 api only mode executable takes about 5Mb

**Comment by buggins** [comment]
Fixed memory leak in OpenGL drawing.
But 70-80Mb RAM for OpenGL version is ok. At least it does not grow.

**Comment by timepp** [comment]
Thanks for the explanation!
